Aress7/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Route_to_Market__c</fullName>
        <description>Route to Markets we use at POD Point</description>
        <inlineHelpText>Please choose a route to market</inlineHelpText>
        <label>Account Route to Market</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Workplace</fullName>
                </value>
                <value>
                    <fullName>Destination</fullName>
                </value>
                <value>
                    <fullName>Built Environment</fullName>
                </value>
                <value>
                    <fullName>Academy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Phase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Phase</label>
        <referenceTo>Phases__c</referenceTo>
        <relationshipLabel>Bidding Companies</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_to_Market__c</fullName>
        <formula>TEXT(Account.Route_to_Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Route to Market</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Bid</fullName>
        <active>true</active>
        <businessProcess>Commercial</businessProcess>
        <label>Bid</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/Phases__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phase_Description__c</fullName>
        <label>Phase Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Phases</relationshipLabel>
        <relationshipName>Phases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tender Produced</fullName>
                </value>
                <value>
                    <fullName>Bids In</fullName>
                </value>
                <value>
                    <fullName>Contract Awarded</fullName>
                </value>
                <value>
                    <fullName>Started on Site</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>On going</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property_Developer__c</fullName>
        <label>Property Developer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/classes/AccountController.cls
public class AccountController {
	public Account Acc;
    public List<Project__c> listProjects{get;set;}
    public List<Phases__c> listPhases{get;set;}
    public List<Opportunity> listBids{get;set;}
    public String projectID {get;set;}
    public String phaseID {get;set;}
    public String routeToMarket {get;set;}
    
    public AccountController(ApexPages.StandardController controller) 
    {
        this.Acc = (Account) controller.getRecord();
        
        getProjectDetails();
        getBids();
    }
    
    public void getProjectDetails() 
    {
        system.debug(Acc);
        set<id> setprojectID = new set<id>();
        
        Account accts = [select id,Route_to_Market__c from account where id =: Acc.id];
        
        routeToMarket = accts.Route_to_Market__c;
        
        //Get all projects which are primary developer for projects.
        listProjects = [Select id,name,Start_Date__c,End_Date__c from Project__c where Property_Developer__c = : accts.id];

    }
    
    public void getPhases() {
        listPhases = [Select id, name , Stage__c,Start_Date__c,End_Date__c,Phase_Description__c from Phases__c where Project__c =:projectID ];
    }
    
    public void getBids() {
        string recordTypeId = [SELECT id from RecordType where Name ='Bid'].Id;
        listBids = [Select id, name , Stagename,account.name,amount,recordtype.name,phase__r.project__r.name,phase__r.project__r.id from Opportunity where recordtypeid =: recordTypeId  and accountid =:this.Acc.id ];
    }
}