Aress7/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <inlineHelpText>Choose the type of account this is.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Route_to_Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Motor Group</fullName>
                </value>
                <value>
                    <fullName>Leasing Company</fullName>
                </value>
                <value>
                    <fullName>Dealer</fullName>
                </value>
                <value>
                    <fullName>Workplace</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Facilities Management</fullName>
                </value>
                <value>
                    <fullName>BE Influencer</fullName>
                </value>
                <value>
                    <fullName>Agents / Developers</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>Business Park</fullName>
                </value>
                <value>
                    <fullName>Depot</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Airport</fullName>
                </value>
                <value>
                    <fullName>Carpark Operator</fullName>
                </value>
                <value>
                    <fullName>Rail</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Attraction</fullName>
                </value>
                <value>
                    <fullName>Holiday Venue</fullName>
                </value>
                <value>
                    <fullName>Car Club</fullName>
                </value>
                <value>
                    <fullName>University</fullName>
                </value>
                <value>
                    <fullName>Hospital</fullName>
                </value>
                <value>
                    <fullName>Grocer</fullName>
                </value>
                <value>
                    <fullName>Taxi</fullName>
                </value>
                <value>
                    <fullName>Sport Venue</fullName>
                </value>
                <value>
                    <fullName>Food/Beverage</fullName>
                </value>
                <value>
                    <fullName>Wildlife</fullName>
                </value>
                <value>
                    <fullName>Health/Wellbeing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>Norway</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Route_to_Market__c</fullName>
        <label>Account Route to Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Workplace</fullName>
                </value>
                <value>
                    <fullName>Destination</fullName>
                </value>
                <value>
                    <fullName>Built Environment</fullName>
                </value>
                <value>
                    <fullName>Insights</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Motor Group</fullName>
                </value>
                <value>
                    <fullName>Leasing Company</fullName>
                </value>
                <value>
                    <fullName>Dealer</fullName>
                </value>
                <value>
                    <fullName>Workplace</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Facilities Management</fullName>
                </value>
                <value>
                    <fullName>BE Influencer</fullName>
                </value>
                <value>
                    <fullName>Agents / Developers</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>Business Park</fullName>
                </value>
                <value>
                    <fullName>Depot</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Airport</fullName>
                </value>
                <value>
                    <fullName>Carpark Operator</fullName>
                </value>
                <value>
                    <fullName>Rail</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Attraction</fullName>
                </value>
                <value>
                    <fullName>Holiday Venue</fullName>
                </value>
                <value>
                    <fullName>Car Club</fullName>
                </value>
                <value>
                    <fullName>University</fullName>
                </value>
                <value>
                    <fullName>Hospital</fullName>
                </value>
                <value>
                    <fullName>Grocer</fullName>
                </value>
                <value>
                    <fullName>Taxi</fullName>
                </value>
                <value>
                    <fullName>Sport Venue</fullName>
                </value>
                <value>
                    <fullName>Food/Beverage</fullName>
                </value>
                <value>
                    <fullName>Wildlife</fullName>
                </value>
                <value>
                    <fullName>Health/Wellbeing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Aress7/src/classes/LeadConversionPageController.cls
public class LeadConversionPageController{

public Boolean bolCreateOpp {get;set;}
public String strAccountId {get;set;}
public String strLeadid {get;set;}
public String OppName {get;set;}
public Lead ldSource {get;set;}
Map<String, String> dict = new Map<String, String>();
Map<String, String> convertleadstatus = new Map<String, String>();
    public LeadConversionPageController(ApexPages.StandardController scMain) {
	   ldSource = [SELECT Id, FirstName, LastName, Name, OwnerId, Company, Street, City, State, PostalCOde, Country, Phone, Fax, Account_Classification__c, Account_Route_to_Market__c, Account_Type__c FROM Lead WHERE Id = :scMain.getId()];
	   bolCreateOpp = false;
       OppName=  ldSource.company;
      
         if(ldSource.Account_Classification__c == null || ldSource.Account_Route_to_Market__c == null || ldSource.Account_Type__c==null){
          ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Add Account Classification, Route to Market and Type before converting this Lead	'));
        
       }
    }

   public List<SelectOption> getlstCompanyInfo() {
      String strCompanyWildcard = '%' + ldSource.Company + '%';
	  List<Account> lstAcct = [SELECT Id, Name, Owner.Name FROM Account WHERE Name LIKE :strCompanyWildcard];
	  List<SelectOption> lstCompanies = new List<SelectOption>();
	 
	  lstCompanies.add(new SelectOption('1','Create New Account: ' + ldSource.Company));
	  // Add found Accounts to SelectList
	  for(Account a : lstAcct) {
	     lstCompanies.add(new SelectOption(a.Id, 'Attach to Existing: ' + a.Name + ' (' + a.Owner.Name + ')'));
         dict.put(a.Id, 'Attach to Existing: ' + a.Name + ' (' + a.Owner.Name + ')');
      }
      return lstCompanies;
   }
   public List<SelectOption> getConvertedStatus(){
       List<SelectOption> ConvertedLeadStatus = new List<SelectOption>();
       List<LeadStatus> convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true];
          for(LeadStatus l : convertStatus) {
	         ConvertedLeadStatus.add(new SelectOption(l.Id,l.MasterLabel));
             convertleadstatus.put(l.id,l.MasterLabel);
	      }
      return ConvertedLeadStatus;		
    }
   public void doNothing() {  }

   public PageReference convertLead() {
	   if(ldSource.Account_Classification__c == null || ldSource.Account_Route_to_Market__c == null || ldSource.Account_Type__c==null){
          ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Add Account Classification, Route to Market and Type before converting this Lead	'));
          return null;
       }
       Database.LeadConvert lc = new Database.LeadConvert();
	   lc.setLeadId(ldSource.Id);
	   lc.setOwnerId(ldSource.OwnerId);
       boolean teeee = lc.isDoNotCreateOpportunity();
       string temp = dict.get(strAccountId);
       string ConvertedleadstatusName = convertleadstatus.get(strLeadid);
       lc.setConvertedStatus(ConvertedleadstatusName);
       if(bolCreateOpp == true && temp == null){
          ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You must create opp when converting lead with new account'));
          return null;
       }
       if(bolCreateOpp == true && temp != null){
          lc.setDoNotCreateOpportunity(true);
         
       }
       if(bolCreateOpp == false && temp == null){
          //lc.setDoNotCreateOpportunity(true);
          lc.setOpportunityName(OppName);  
       }
       
	   if(strAccountId.length() > 1) { 
          lc.setAccountId(strAccountId);
       }
       //if(strLeadId.length() > 1) { 
          
       //}
	   Database.LeadConvertResult lcr = Database.convertLead(lc);
	   PageReference prResult;
	   if(lcr.isSuccess()) {
	      prResult = new PageReference('/' + lcr.getAccountId());
		  prResult.setRedirect(true);
		  return prResult;	
	   } else {
	        return null;
	     }
	
   }
    
}