Aress7/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Picklist__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote_2__c</fullName>
        <label>Total Install Cost 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <label>Total Install Cost 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Hours_2__c</fullName>
        <label>Labour 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Hours__c</fullName>
        <label>Labour 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OLEV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OLEV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>Postcode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <label>Project Manager</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amy Lambourne</fullName>
                </value>
                <value>
                    <fullName>Arne Nikolaus</fullName>
                </value>
                <value>
                    <fullName>Martin Miles</fullName>
                </value>
                <value>
                    <fullName>Richard Wise</fullName>
                </value>
                <value>
                    <fullName>Shauna Black</fullName>
                </value>
                <value>
                    <fullName>Bradley Turk</fullName>
                </value>
                <value>
                    <fullName>Joshua Doyle-Tanner</fullName>
                </value>
                <value>
                    <fullName>Kostas Papadakis</fullName>
                </value>
                <value>
                    <fullName>Alex McKinney</fullName>
                </value>
                <value>
                    <fullName>Stuart Clark</fullName>
                </value>
                <value>
                    <fullName>Richard Lindop</fullName>
                </value>
                <value>
                    <fullName>James Farrier</fullName>
                </value>
                <value>
                    <fullName>Sam Biggs</fullName>
                </value>
                <value>
                    <fullName>Richard King</fullName>
                </value>
                <value>
                    <fullName>Jagdish Nikam</fullName>
                </value>
                <value>
                    <fullName>Stephen Kellett</fullName>
                </value>
                <value>
                    <fullName>Christos Polydoros</fullName>
                </value>
                <value>
                    <fullName>Bryan Saignasith</fullName>
                </value>
                <value>
                    <fullName>Matt Preston</fullName>
                </value>
                <value>
                    <fullName>Cameron Mclean</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scope_of_Work__c</fullName>
        <label>Scope of Work 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scope_of_Works_2__c</fullName>
        <label>Scope of Works 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status (old)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <label>UUID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_PSL_PG_Number__c</fullName>
        <label>Unit PSL/PG Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/FSL_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Work_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Type</label>
        <referenceTo>WorkType</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FSL Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FSL Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country_Picklist__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Postal_Code__c</fullName>
        <label>Billing Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote_2__c</fullName>
        <inlineHelpText>Don&apos;t forget to add margin!</inlineHelpText>
        <label>Install Quote 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <inlineHelpText>Don&apos;t forget to add margin!</inlineHelpText>
        <label>Install Quote 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Hours_2__c</fullName>
        <label>Install Hours 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Hours__c</fullName>
        <label>Install Hours 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <label>Project Manager</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scope_of_Work__c</fullName>
        <label>Scope of Work 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Shipping_City__c</fullName>
        <label>Shipping City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Country_Picklist__c</fullName>
        <label>Shipping Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipping_Postal_Code__c</fullName>
        <label>Shipping Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Street__c</fullName>
        <label>Shipping Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sockets__c</fullName>
        <label>Total Sockets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Commercial</fullName>
        <active>true</active>
        <businessProcess>Commercial</businessProcess>
        <label>Commercial</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <label>Install Cost Quote</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sockets__c</fullName>
        <formula>PricebookEntry.Product2.Sockets__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sockets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Aress7/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Sockets__c</fullName>
        <inlineHelpText>Number of Sockets on Unit</inlineHelpText>
        <label>Sockets</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/objects/ProductRequired.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Products Required</relationshipLabel>
        <relationshipName>Products_Required</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Notes_about_your_order__c</fullName>
        <inlineHelpText>Notes for Supply Team</inlineHelpText>
        <label>Order Notes</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Main_SA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is checked if the service appointment is Main Service Appointment</description>
        <label>Main SA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Case__r.Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <formula>text( Case__r.Project_Manager__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Type__c</fullName>
        <label>Work Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/objects/Work_Order_Task__c.object
<CustomObject>
    <fields>
        <fullName>Annex_D_Form__c</fullName>
        <description>- Fill out Signee Name and Relationship if different from customer
- Return to Work Order 
- Select &quot;Create Service Report&quot; on the quick action
- Complete &quot;Customer Signature&quot; and &quot;Installer Signature&quot;
- Click Generate Signed Report to complete</description>
        <label>Annex D Form</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Signee_Name__c</fullName>
        <label>Signee Name (If not customer)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signee_Relationship__c</fullName>
        <label>Signee Relationship (If not customer)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>FSL_Tasks__c</referenceTo>
        <relationshipLabel>Work Order Tasks</relationshipLabel>
        <relationshipName>Work_Order_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_PSL_PG_number__c</fullName>
        <label>Unit PSL/PG number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Work Order Tasks</relationshipLabel>
        <relationshipName>Work_Order_Tasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Order Task</label>
    <nameField>
        <displayFormat>WOT-{00000}</displayFormat>
        <label>Work Order Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OLEV__c</fullName>
        <formula>Case.OLEV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OLEV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Case.Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <formula>TEXT(Case.Project_Manager__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <formula>Case.UUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UUID</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Survey</fullName>
        <active>true</active>
        <label>Survey</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/classes/QuoteTriggerHandlerNew_Test.cls
@isTest
public class QuoteTriggerHandlerNew_Test {
    
    static testMethod void createCommCaseTest2(){
        
        
        
        Account Acc = new Account(Name='Test Account');
        insert Acc;
        Contact con = new Contact(Lastname = 'Test Contact',accountid=acc.id, email = 'test@test.com');
        insert con;
        Product2 prod = new Product2(Name = 'Accommodation',Sockets__c=5,ProductCode = 'Mngd_Inst', Family = 'Twin Units',CurrencyIsoCode='GBP',IsActive=true);
        insert prod;
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod.Id,UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        Pricebook2 customPB = new Pricebook2(Name='Podpoint - Meetings & Events', isActive=true);
        insert customPB;
        
        // PricebookEntry customPrice = new PricebookEntry(Pricebook2Id = customPB.Id, Product2Id = prod.Id,UnitPrice = 12000, IsActive = true);
        //  insert customPrice;
        
        //  Pricebook2 customPB1 = new Pricebook2(Name='Podpoint - OnlinePayment', isActive=true);
        //   insert customPB1;
        
        //  PricebookEntry customPrice1 = new PricebookEntry(Pricebook2Id = customPB1.Id, Product2Id = prod.Id,UnitPrice = 12000, IsActive = true);
        //  insert customPrice1;
        
        
        Opportunity opp = new Opportunity();
        opp.Name='test';
        opp.StageName='new';
        opp.AccountId=acc.Id;
        opp.CloseDate=system.today();
        opp.RecordTypeId = [Select Id,SobjectType,DeveloperName From RecordType where DeveloperName ='Commercial' and SobjectType ='Opportunity' limit 1].Id;
        Insert opp;
        //(Name='Test Opportunity',accountid=acc.id,closedate=System.today(),StageName='Qualification',shipping_street__c='TestStreet',Shipping_City__c='TestCity', Shipping_Postal_Code__c='TestPostalCode', Shipping_Country_Picklist__c='United Kingdom');
        //opp.RecordTypeId = [Select Id,SobjectType,DeveloperName From RecordType where DeveloperName ='Commercial' and SobjectType ='Opportunity' limit 1].Id;
        //Insert opp;
        
        OpportunityLineItem ol = new OpportunityLineItem();
        ol.OpportunityId=opp.Id;
        ol.PricebookEntryId=standardPrice.Id;
        ol.Product2Id=prod.Id;
        ol.UnitPrice=12;
        ol.Quantity=1;
        insert ol;
        
        //(OpportunityId = opp.id,PricebookEntryId = customPrice1.id,Product2Id = prod.id,UnitPrice = 10,Quantity = 2);
        //List<OpportunityLineItem> olList = new List<OpportunityLineItem>();
        //olList.add(ol);
        //insert olList;
        //insert ol;
        List<String> OpptyIds = new List<String>();
        OpptyIds.add(String.valueOf(opp.Id));
        
        OpportunityContactRole ocr1 = new OpportunityContactRole(opportunityid=opp.id,contactid=con.id,IsPrimary=true);
        insert ocr1;
        
        
        Id CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Case').getRecordTypeId();
        case cs = new case(AccountId=opp.AccountId,RecordTypeId=CaseRecordTypeId, Type='Commercial', Opportunity__c=opp.Id, ContactId=con.Id,Street__c=opp.Shipping_Street__c, City__c=opp.Shipping_City__c, PostalCode__c=opp.Shipping_Postal_Code__c, Country_Picklist__c=opp.Shipping_Country_Picklist__c);
        cs.Project_Manager__c = 'Kostas';
        //Insert cs;
        //cs.Project_Manager__c = 'Kostas';
        //update cs;
        
        //WorkType data
        WorkType wt= new WorkType(Name='Install (Commercial)',DurationType='Hours',EstimatedDuration=2);
        wt.ShouldAutoCreateSvcAppt=true;
        Insert wt;
        WorkType wt1= new WorkType(Name='Install (Domestic)',DurationType='Hours',EstimatedDuration=2);
        Insert wt1;
        
        
        Opportunity opp2 = new Opportunity();
        opp2.Name='test';
        opp2.StageName='new';
        opp2.AccountId=acc.Id;
        opp2.CloseDate=system.today();
        opp2.RecordTypeId = [Select Id,SobjectType,DeveloperName From RecordType where DeveloperName ='Commercial' and SobjectType ='Opportunity' limit 1].Id;
        Insert opp2;
        //(Name='Test Opportunity',accountid=acc.id,closedate=System.today(),StageName='Qualification',shipping_street__c='TestStreet',Shipping_City__c='TestCity', Shipping_Postal_Code__c='TestPostalCode', Shipping_Country_Picklist__c='United Kingdom');
        //opp.RecordTypeId = [Select Id,SobjectType,DeveloperName From RecordType where DeveloperName ='Commercial' and SobjectType ='Opportunity' limit 1].Id;
        //Insert opp;
        
        OpportunityLineItem ol2 = new OpportunityLineItem();
        ol2.OpportunityId=opp2.Id;
        ol2.PricebookEntryId=standardPrice.Id;
        ol2.Product2Id=prod.Id;
        ol2.UnitPrice=12;
        ol2.Quantity=1;
        insert ol2;
        OpportunityContactRole ocr2 = new OpportunityContactRole(opportunityid=opp2.id,contactid=con.id,IsPrimary=true);
        insert ocr2;
        List<String> OpptyIds2 = new List<String>();
        OpptyIds2.add(String.valueOf(opp2.Id));
        
        
        test.startTest();
        // QuoteTriggerHandlerNew.createCommCase(OpptyIds);
          Quote qt = new Quote(name='Test Quote',opportunityid=opp.id,shippingstreet='test street',billingstreet='test street',shippingcity = 'City',billingcity = 'City',shippingpostalcode = '123',billingpostalcode = '123' ,Notes_about_your_order__c='test note');
        Insert qt;
        Map<Id,Quote> test2=new Map<Id,Quote>();
        test2.put(opp.id,qt);
        QuoteTriggerHandlerNew.createCommCase(test2);
        test.stopTest();
    }
    
    static testMethod void createCommCaseTest3(){
        Account Acc = new Account(Name='Test Account');
        insert Acc;
        Contact con = new Contact(Lastname = 'Test Contact',accountid=acc.id);
        insert con;
        Product2 prod = new Product2(Name = 'Accommodation',Sockets__c=5,ProductCode = 'Mngd_Inst', Family = 'Twin Units',CurrencyIsoCode='GBP',IsActive=true);
        insert prod;
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod.Id,UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        Pricebook2 customPB = new Pricebook2(Name='Podpoint - Meetings & Events', isActive=true);
        insert customPB;
        
        // PricebookEntry customPrice = new PricebookEntry(Pricebook2Id = customPB.Id, Product2Id = prod.Id,UnitPrice = 12000, IsActive = true);
        //  insert customPrice;
        
        //  Pricebook2 customPB1 = new Pricebook2(Name='Podpoint - OnlinePayment', isActive=true);
        //   insert customPB1;
        
        //  PricebookEntry customPrice1 = new PricebookEntry(Pricebook2Id = customPB1.Id, Product2Id = prod.Id,UnitPrice = 12000, IsActive = true);
        //  insert customPrice1;
        
        
        Opportunity opp = new Opportunity();
        opp.Name='test';
        opp.StageName='new';
        opp.AccountId=acc.Id;
        opp.CloseDate=system.today();
        opp.RecordTypeId = [Select Id,SobjectType,DeveloperName From RecordType where DeveloperName ='Commercial' and SobjectType ='Opportunity' limit 1].Id;
        Insert opp;
        //(Name='Test Opportunity',accountid=acc.id,closedate=System.today(),StageName='Qualification',shipping_street__c='TestStreet',Shipping_City__c='TestCity', Shipping_Postal_Code__c='TestPostalCode', Shipping_Country_Picklist__c='United Kingdom');
        //opp.RecordTypeId = [Select Id,SobjectType,DeveloperName From RecordType where DeveloperName ='Commercial' and SobjectType ='Opportunity' limit 1].Id;
        //Insert opp;
        
        OpportunityLineItem ol = new OpportunityLineItem();
        ol.OpportunityId=opp.Id;
        ol.PricebookEntryId=standardPrice.Id;
        ol.Product2Id=prod.Id;
        ol.UnitPrice=12;
        ol.Quantity=1;
        insert ol;
        
        //(OpportunityId = opp.id,PricebookEntryId = customPrice1.id,Product2Id = prod.id,UnitPrice = 10,Quantity = 2);
        //List<OpportunityLineItem> olList = new List<OpportunityLineItem>();
        //olList.add(ol);
        //insert olList;
        //insert ol;
        List<String> OpptyIds = new List<String>();
        OpptyIds.add(String.valueOf(opp.Id));
        
        OpportunityContactRole ocr1 = new OpportunityContactRole(opportunityid=opp.id,contactid=con.id,IsPrimary=true);
        insert ocr1;
        
        
        Id CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Case').getRecordTypeId();
        case cs = new case(AccountId=opp.AccountId,RecordTypeId=CaseRecordTypeId, Type='Commercial', Opportunity__c=opp.Id, ContactId=con.Id,Street__c=opp.Shipping_Street__c, City__c=opp.Shipping_City__c, PostalCode__c=opp.Shipping_Postal_Code__c, Country_Picklist__c=opp.Shipping_Country_Picklist__c);
        cs.Project_Manager__c = 'Kostas';
        Insert cs;
        //cs.Project_Manager__c = 'Kostas';
        //update cs;
        
        //WorkType data
        WorkType wt= new WorkType(Name='Install (Commercial)',DurationType='Hours',EstimatedDuration=2);
        Insert wt;
        WorkType wt1= new WorkType(Name='Install (Domestic)',DurationType='Hours',EstimatedDuration=2);
        Insert wt1;
        
        test.startTest();
                  Quote qt = new Quote(name='Test Quote',opportunityid=opp.id,shippingstreet='test street',billingstreet='test street',shippingcity = 'City',billingcity = 'City',shippingpostalcode = '123',billingpostalcode = '123' ,Notes_about_your_order__c='test note');
        Insert qt;
        Map<Id,Quote> test2=new Map<Id,Quote>();
        test2.put(opp.id,qt);
                Test.setMock(HttpCalloutMock.class, new OtMockHttpResponseGenerator());

        QuoteTriggerHandlerNew.createCommCase(test2);
        // QuoteTriggerHandlerNew.createCommCase(OpptyIds2);
        test.stopTest();
    }
    
  /*  public static testmethod void test03(){
        Set<Id> WOId = new Set<Id>();
        List<String> OppId = new List<String>();
        
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
                                  lastName = 'test',type = 'Prospect');
        insert acc;
          Contact con = new Contact(Lastname = 'Test Contact',accountid=acc.id, email = 'test@test.com');
        insert con;
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
                                          Name = 'Test Opp',
                                          AccountId = acc.id,
                                          closedate = Date.today(),
                                          Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Billing_Postal_Code__c = 'Test',
                                          Billing_Street__c = 'Test',
                                          Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Shipping_Postal_Code__c = 'Test',
                                          Shipping_Street__c = 'Test',
                                          StageName = 'New');
        insert opp;     
         OpportunityContactRole ocr1 = new OpportunityContactRole(opportunityid=opp.id,contactid=con.id,IsPrimary=true);
        insert ocr1;
        Case cs = new Case(street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
                           Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
                           Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',UUID__c='1223456');
        cs.OLEV__c=true;
        insert cs;
        
        List<worktype> wtList=new List<WorkType>();
        worktype wt =new worktype(Name='Install (Commercial)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt);
        worktype wt1 =new worktype(Name='Install (Domestic)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt1);
        worktype wt2 =new worktype(Name='Additional Works (Domestic)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt2);
        insert wtList;
        
        Id hcInstallWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        List<WorkOrder> woList=new List<WorkOrder>();
        WorkOrder wo1= new WorkOrder(Status='Active',RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id);
        woList.add(wo1) ;
        //WorkOrder wo2= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id);
        //woList.add(wo2) ;
        insert woList;
        
        ServiceAppointment sa = new ServiceAppointment();
        sa.EarliestStartTime=System.today();
        sa.DueDate=System.today()+1;
        sa.Status='Completed';
        sa.SchedStartTime=System.today();
        sa.SchedEndTime=System.today()+1;
        sa.ParentRecordId=wo1.id;
        sa.ArrivalWindowStartTime=System.today();
        sa.ArrivalWindowEndTime=System.today()+1;
        sa.Main_SA__c=true;
        insert sa;
        
        
        
        List<FSL_Tasks__c> fslTaskList = new List<FSL_Tasks__c>();
        FSL_Tasks__c fslTask = new FSL_Tasks__c(Name = 'Unit PSL/PG Number',Work_Type__c =wt1.Id);
        FSL_Tasks__c fslTask1 = new FSL_Tasks__c(Name = 'Annex D Form',Work_Type__c =wt1.Id);
        fslTaskList.add(fslTask);
        fslTaskList.add(fslTask1);
        Insert fslTaskList;
        
        List<Work_Order_Task__c> wotaskList1= new List<Work_Order_Task__c>();
        Work_Order_Task__c wot = new Work_Order_Task__c(Work_Order__c=wo1.Id, Signee_Name__c='testSignee', Signee_Relationship__c='TestRelationship', Unit_PSL_PG_number__c='testPgNo', Annex_D_Form__c='testForm1', Task__c=fslTask.Id);
        wot.Status__c='Completed';
        Work_Order_Task__c wot1 = new Work_Order_Task__c(Work_Order__c=wo1.Id, Signee_Name__c='testSignee', Signee_Relationship__c='TestRelationship1', Unit_PSL_PG_number__c='testPgNo1', Annex_D_Form__c='testForm2', Task__c=fslTask1.Id);
        wot1.Status__c='Completed';
        wotaskList1.add(wot);
        wotaskList1.add(wot1);
        Insert wotaskList1;
        
        
        List<WorkOrder> woListToUpdate=new List<WorkOrder>();
        wo1.Status='Completed';
        //update wo1;
        woListToUpdate.add(wo1);
        //wo2.Status='Confirmed';
        //woListToUpdate.add(wo2);
        //update woListToUpdate;
        
        List<Work_Order_Task__c> wotaskList= new List<Work_Order_Task__c>([SELECT Work_Order__c, Status__c, Id, Task__c FROM Work_Order_Task__c where Work_Order__c=:wo1.Id]);
        // for(Work_Order_Task__c wot : wotaskList){
        //     wot.Status__c='Completed';
        
        // }
        //  delete wotaskList;
        List<ServiceAppointment> saList= new List<ServiceAppointment>([SELECT Id, ParentRecordId, Status FROM ServiceAppointment where ParentRecordId=:wo1.Id]);
        // for(ServiceAppointment sa: saList){
        //     sa.Status='Completed';
        // }
        delete saList;        
        
        
        
        
        WOId.add(wo1.Id);
        //WOId.add(wo2.Id);
        //WOId.add(wo2.Id);
        
        OppId.add(opp.Id);
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Product2 prod = new Product2(
            Name = 'Product X',
            ProductCode = 'Pro-X',
            isActive = true
        );
        insert prod;
        
        //Create your pricebook entry
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        
        //create your opportunity line item.  This assumes you already have an opportunity created, called opp
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = opp.Id;
        oli.Quantity = 5;
        oli.PricebookEntryId = pbEntry.Id;
        oli.Product2Id=prod.id;
        oli.OpportunityId=opp.Id;
        // oli.TotalPrice=Quantity * pbEntry.UnitPrice;
        oli.TotalPrice=oli.Quantity * pbEntry.UnitPrice;
        insert oli;
        
        List<ProductRequired> Prodlst = new List<ProductRequired>(); 
        
        ProductRequired pr = new ProductRequired();
        pr.ParentRecordId = wo1.Id;
        pr.Product2Id = oli.Product2Id;
        pr.Opportunity__c = oli.OpportunityId;
        pr.QuantityRequired = oli.Quantity;
        system.debug('pr.QuantityRequired' + pr.QuantityRequired);
        pr.WO_OppLineItem_Id__c = oli.id;
        Prodlst.add(pr);
        
        Map<Id,WorkOrder> WOMap = new Map<Id,WorkOrder>();
        WOMap.put(wo1.Id, wo1);
        
        Map<Id, OpportunityLineItem> oliMap = new Map<Id, OpportunityLineItem>();
        oliMap.put(oli.Id, oli);
        Test.startTest();
        //Test.setMock(HttpCalloutMock.class, new OtMockHttpResponseGenerator());
                         Quote qt = new Quote(name='Test Quote',opportunityid=opp.id,shippingstreet='test street',billingstreet='test street',shippingcity = 'City',billingcity = 'City',shippingpostalcode = '123',billingpostalcode = '123' ,Notes_about_your_order__c='test note');
        Insert qt;
        Map<Id,Quote> test2=new Map<Id,Quote>();
        test2.put(opp.id,qt);
        QuoteTriggerHandlerNew.createCommCase(test2);
       // QuoteTriggerHandlerNew.createCommCase(OppId);
        Test.stopTest();
    }*/
    
    static testMethod void test04(){
        Account Acc = new Account(Name='Test Account');
        insert Acc;
        Contact con = new Contact(Lastname = 'Test Contact',accountid=acc.id);
        insert con;
        Product2 prod = new Product2(Name = 'Accommodation',Sockets__c=5,ProductCode = 'Mngd_Inst', Family = 'Twin Units',CurrencyIsoCode='GBP',IsActive=true);
        insert prod;
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod.Id,UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        Pricebook2 customPB = new Pricebook2(Name='Podpoint - Meetings & Events', isActive=true);
        insert customPB;
        Opportunity opp = new Opportunity();
        opp.Name='test';
        opp.StageName='new';
        opp.AccountId=acc.Id;
        opp.CloseDate=system.today();
        
        opp.RecordTypeId = [Select Id,SobjectType,DeveloperName From RecordType where DeveloperName ='Commercial' and SobjectType ='Opportunity' limit 1].Id;
        Insert opp;
        
        OpportunityLineItem ol = new OpportunityLineItem();
        ol.OpportunityId=opp.Id;
        ol.PricebookEntryId=standardPrice.Id;
        ol.Product2Id=prod.Id;
        ol.UnitPrice=12;
        ol.Quantity=1;
        insert ol;
        List<String> OpptyIds = new List<String>();
        OpptyIds.add(String.valueOf(opp.Id));
        
        OpportunityContactRole ocr1 = new OpportunityContactRole(opportunityid=opp.id,contactid=con.id,IsPrimary=true);
        insert ocr1;
        
        
        Id CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Case').getRecordTypeId();
        case cs = new case(AccountId=opp.AccountId,RecordTypeId=CaseRecordTypeId, Type='Commercial', Opportunity__c=opp.Id, ContactId=con.Id,Street__c=opp.Shipping_Street__c, City__c=opp.Shipping_City__c, PostalCode__c=opp.Shipping_Postal_Code__c, Country_Picklist__c=opp.Shipping_Country_Picklist__c);
        cs.Project_Manager__c = 'Kostas';
        Insert cs;
        
        case cs2 = new case(AccountId=opp.AccountId,RecordTypeId=CaseRecordTypeId, Type='Commercial', Opportunity__c=opp.Id, ContactId=con.Id,Street__c=opp.Shipping_Street__c, City__c=opp.Shipping_City__c, PostalCode__c=opp.Shipping_Postal_Code__c, Country_Picklist__c=opp.Shipping_Country_Picklist__c);
        cs2.Project_Manager__c = 'Kostas';
        Insert cs2;
        
        WorkType wt= new WorkType(Name='Install (Commercial)',DurationType='Hours',EstimatedDuration=2);
        Insert wt;
        WorkType wt1= new WorkType(Name='Install (Domestic)',DurationType='Hours',EstimatedDuration=2);
        Insert wt1;
        
        
        Opportunity opp2 = new Opportunity();
        opp2.Name='test';
        opp2.StageName='new';
        opp2.AccountId=acc.Id;
        opp2.CloseDate=system.today();
        opp2.RecordTypeId = [Select Id,SobjectType,DeveloperName From RecordType where DeveloperName ='Commercial' and SobjectType ='Opportunity' limit 1].Id;
        Insert opp2;
        
        OpportunityLineItem ol2 = new OpportunityLineItem();
        ol2.OpportunityId=opp2.Id;
        ol2.PricebookEntryId=standardPrice.Id;
        ol2.Product2Id=prod.Id;
        ol2.UnitPrice=12;
        ol2.Quantity=1;
        insert ol2;
        OpportunityContactRole ocr2 = new OpportunityContactRole(opportunityid=opp2.id,contactid=con.id,IsPrimary=true);
        insert ocr2;
        List<String> OpptyIds2 = new List<String>();
        OpptyIds2.add(String.valueOf(opp2.Id));
        
        Id workOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Commercial Install').getRecordTypeId();
        
        WorkOrder wo=new WorkOrder(RecordTypeId=workOrderId,WorkTypeId=wt.id,CaseId=cs.id,Status='Incomplete');
        
        
        List<WorkOrder> woList=new List<WorkOrder>();
        woList.add(wo);
        Map<String,List<WorkOrder>> caseWOMap = new Map<String,List<WorkOrder>>();
        caseWOMap.put(String.valueOf(cs.id), woList);
        
        test.startTest();
        QuoteTriggerHandler.createCommercialCase(String.valueOf(acc.id), caseWOMap, opp);
        QuoteTriggerHandler.afterUpdateQuoteHandle(OpptyIds);
        QuoteTriggerHandler.createCommercialCase(String.valueOf(acc.id), caseWOMap, opp2);
        
        test.stopTest();
    }
    
    
    /*   
static testMethod void createCommCaseTest()
{
//Create a test account
Account Acc = new Account(Name='Test Account');
insert Acc;

Contact con = new Contact(Lastname = 'Test Contact',accountid=acc.id);
insert con;

Product2 prod = new Product2(Name = 'Accommodation',Sockets__c=5,ProductCode = 'Mngd_Inst', Family = 'Twin Units',CurrencyIsoCode='GBP',IsActive=true);
insert prod;

Id pricebookId = Test.getStandardPricebookId();
PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod.Id,UnitPrice = 10000, IsActive = true);
insert standardPrice;

Pricebook2 customPB = new Pricebook2(Name='Podpoint - Meetings & Events', isActive=true);
insert customPB;

PricebookEntry customPrice = new PricebookEntry(Pricebook2Id = customPB.Id, Product2Id = prod.Id,UnitPrice = 12000, IsActive = true);
insert customPrice;

Pricebook2 customPB1 = new Pricebook2(Name='Podpoint - OnlinePayment', isActive=true);
insert customPB1;

PricebookEntry customPrice1 = new PricebookEntry(Pricebook2Id = customPB1.Id, Product2Id = prod.Id,UnitPrice = 12000, IsActive = true);
insert customPrice1;

Id bookingid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId();

//Create a test opportunity
List<String> OpptyIds = new List<String>();
Opportunity opp = new Opportunity(Name='Test Opportunity',accountid=acc.id,closedate=System.today(),StageName='Qualification',shipping_street__c='TestStreet',Shipping_City__c='TestCity', Shipping_Postal_Code__c='TestPostalCode', Shipping_Country_Picklist__c='United Kingdom');
opp.RecordTypeId = [Select Id,SobjectType,DeveloperName From RecordType where DeveloperName ='Commercial' and SobjectType ='Opportunity' limit 1].Id;
Insert opp;

OpportunityLineItem ol = new OpportunityLineItem(OpportunityId = opp.id,PricebookEntryId = customPrice1.id,Product2Id = prod.id,UnitPrice = 10,Quantity = 2);
//List<OpportunityLineItem> olList = new List<OpportunityLineItem>();
//olList.add(ol);
//insert olList;
insert ol;

OpptyIds.add(opp.Id);

OpportunityContactRole ocr1 = new OpportunityContactRole(opportunityid=opp.id,contactid=con.id,IsPrimary=true);
insert ocr1;


Id CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Case').getRecordTypeId();
case cs = new case(AccountId=opp.AccountId,RecordTypeId=CaseRecordTypeId, Type='Commercial', Opportunity__c=opp.Id, ContactId=con.Id,Street__c=opp.Shipping_Street__c, City__c=opp.Shipping_City__c, PostalCode__c=opp.Shipping_Postal_Code__c, Country_Picklist__c=opp.Shipping_Country_Picklist__c);
cs.Project_Manager__c = 'Kostas';
Insert cs;
//cs.Project_Manager__c = 'Kostas';
//update cs;

//WorkType data
WorkType wt= new WorkType(Name='Install (Commercial)',DurationType='Hours',EstimatedDuration=2);
Insert wt;
WorkType wt1= new WorkType(Name='Install (Domestic)',DurationType='Hours',EstimatedDuration=2);
Insert wt1;

Id woRecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Commercial Install').getRecordTypeId();
WorkOrder w1= new WorkOrder(ContactId=con.Id,AccountId=opp.AccountId,RecordTypeId = woRecordTypeId ,Priority='Medium',WorkTypeId = wt.Id ,Status = 'Unassigned',CaseId = cs.id);
Insert w1;

//Create a test quote
Quote qt = new Quote(name='Test Quote',opportunityid=opp.id,shippingstreet='test street',billingstreet='test street',shippingcity = 'City',billingcity = 'City',shippingpostalcode = '123',billingpostalcode = '123' ,Notes_about_your_order__c='test note');
Insert qt;

String bodyStr='Test Body';

Attachment att=new Attachment();
att.Body=Blob.valueOf(bodyStr);
att.Name='Note_' + System.now().format('yyyy_MM_dd_hh_mm_ss') + '.txt';
att.parentId=qt.id;
insert att;

opp.SyncedQuoteId =qt.id;
update opp;       
//Change the status to accepted. It will custom error written in the trigger as there will be no attachment.
//qt.Status = 'Accepted';
//qt.IsSyncing='True';

//update qt;
QuoteTriggerHandlerNew.createCommCase(OpptyIds);

}

*/
    
}