Aress7/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Picklist__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote_2__c</fullName>
        <label>Total Install Cost 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <label>Total Install Cost 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Hours_2__c</fullName>
        <label>Labour 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Hours__c</fullName>
        <label>Labour 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>Postcode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scope_of_Work__c</fullName>
        <label>Scope of Work 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scope_of_Works_2__c</fullName>
        <label>Scope of Works 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote_2__c</fullName>
        <inlineHelpText>Don&apos;t forget to add margin!</inlineHelpText>
        <label>Install Quote 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <inlineHelpText>Don&apos;t forget to add margin!</inlineHelpText>
        <label>Install Quote 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Hours_2__c</fullName>
        <label>Install Hours 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Hours__c</fullName>
        <label>Install Hours 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scope_of_Work__c</fullName>
        <label>Scope of Work 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Shipping_City__c</fullName>
        <label>Shipping City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Country__c</fullName>
        <label>Shipping Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_State__c</fullName>
        <label>Shipping State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Street__c</fullName>
        <label>Shipping Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Bid</fullName>
        <active>true</active>
        <businessProcess>Commercial</businessProcess>
        <label>Bid</label>
    </recordTypes>
    <recordTypes>
        <fullName>Commercial</fullName>
        <active>true</active>
        <businessProcess>Commercial</businessProcess>
        <label>Commercial</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Case.Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/classes/QuoteTriggerHandler.cls
public class QuoteTriggerHandler {
public static boolean run = true;

//Create Commercial Case for commercial oppty and Bid oppty
//@Future(Callout=true)
public static void createCommercialCase(String AccountID,Map<String,List<WorkOrder>> caseWOMap,Opportunity oppty ){//,List<Case> CommercialCases,List<OpportunityContactRole> contRoles){
    Case cs = new Case();
    WorkOrder wOrder = new WorkOrder();
    
    //List<Opportunity> oppties = [SELECT ID,Name,Shipping_City__c,Shipping_Street__c,Shipping_State__c, Shipping_Country__c FROM Opportunity WHERE ID =:oppty.Id];
    
   // List<Case> commCases = [SELECT Id,(SELECT ID,RecordType.Name FROM WorkOrders WHERE RecordType.Name='Commercial Install'),RecordType.Name FROM Case WHERE RecordType.Name='Commercial Case'];
    List<WorkOrder> wOrders = new List<WorkOrder>();
    WorkType wt = [select id, name from WorkType where name='Install (Commercial)' LIMIT 1];
    Id cwoRecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Commercial Install').getRecordTypeId();
    Id ccRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Case').getRecordTypeId();
    System.debug('caseWOMap=>'+caseWOMap);
    System.debug('oppty=>'+oppty);
    
    List<Opportunity> opptyList = [SELECT ID,Name,Shipping_City__c,Shipping_Street__c,Shipping_State__c, Shipping_Country__c,
    (SELECT Id,RecordTypeId,Opportunity__c,AccountId,Street__c,City__c,Country_Picklist__c,Type FROM Cases__r)
    FROM Opportunity WHERE ID =:oppty.Id];
    
    List<Case> caseList= [select id,casenumber,street__c,city__c,country_picklist__c,postalcode__c,Opportunity__c,
                  Install_Cost_Quote_2__c,Install_Cost_Quote__c,Install_Hours_2__c,Install_Hours__c,
                  Scope_of_Work__c,Scope_of_Works_2__c,
                  (SELECT ID,RecordType.Name,Status FROM WorkOrders WHERE RecordType.Name='Commercial Install' AND (Status='Completed' OR Status='Incomplete' OR Status='Rejected'))
                  from case where Type = 'Commercial' AND Opportunity__c =:oppty.Id];
    
    for(Opportunity opptyRec:opptyList){
        if(caseList.isEmpty()){
            cs.RecordTypeId = ccRecordTypeId;
            cs.Opportunity__c = oppty.Id;
            cs.AccountId = AccountID;
            //cs.ContactId = contRoles[0].Id;
            cs.Street__c = opptyRec.Shipping_Street__c;
            cs.City__c = opptyRec.Shipping_City__c;
            cs.Country_Picklist__c = opptyRec.Shipping_Country__c;
            //PostalCode__c = oppties[0].
            cs.Type = 'Commercial';
            
            insert cs;
            
            wOrder.RecordTypeId = cwoRecordTypeId;
            wOrder.WorkTypeId = wt.Id ;
            wOrder.Status = 'Confirmed';
            wOrder.CaseId = cs.Id;
            wOrders.add(wOrder);
           // insert wOrders;
        }else{
            for(Case caseRec:caseList){
                if(caseRec.WorkOrders.size()>0){
                    for(WorkOrder wo:caseRec.WorkOrders){
                        if(wo.Status=='Complete'||wo.Status=='Incomplete'||wo.Status=='Rejected'){
                                wOrders.add(new WorkOrder(RecordTypeId = cwoRecordTypeId,WorkTypeId = wt.Id ,Status = 'Confirmed',CaseId = caseRec.Id));
                            }else{
                            caseRec.addError('There is already a pending Install.');
                        }
                    }
                }//else{
                 //    caseRec.addError('There is already a pending Install.');
                 //   }
            }
        }
    }
    insert wOrders;
    /*if(CommercialCases != null){
        if(CommercialCases.size()>0){
            //List<Case> commCases = [SELECT Id,(SELECT ID,RecordType.Name FROM WorkOrders WHERE RecordType.Name='Commercial Install'),RecordType.Name FROM Case WHERE RecordType.Name='Commercial Case'];
            for(Case c:commCases){
                for(WorkOrder wo:c.WorkOrders){
                    if(wo.Status=='Complete'||wo.Status=='Incomplete'||wo.Status=='Rejected'){
                        wOrders.add(new WorkOrder(RecordTypeId = cwoRecordTypeId,WorkTypeId = wt.Id ,Status = 'Confirmed',CaseId = c.Id));
                    }
                    else{
                        wo.addError('There is already a pending Install.');
                    }
                }
            }
            insert wOrders;
        }
        else{
            cs.RecordTypeId = ccRecordTypeId;
            cs.Opportunity__c = OppID;
            cs.AccountId = AccountID;
            //cs.ContactId = contRoles[0].Id;
            cs.Street__c = oppties[0].Shipping_Street__c;
            cs.City__c = oppties[0].Shipping_City__c;
            cs.Country_Picklist__c = oppties[0].Shipping_Country__c;
            //PostalCode__c = oppties[0].
            cs.Type = 'Commercial';
            
            insert cs;
            
            wOrder.RecordTypeId = cwoRecordTypeId;
            wOrder.WorkTypeId = wt.Id ;
            wOrder.Status = 'Confirmed';
            wOrder.CaseId = cs.Id;
            wOrders.add(wOrder);
            insert wOrders;
        }
    }  */      
    //else{
        
    //}
   // return cs;
}

public static Map<id,Opportunity> oppMap;
Public static void afterUpdateQuoteHandle(List<String> opptIds){//,List<OpportunityContactRole> OpptycontactRoles){
    boolean hasManagedInstallProduct = false;
    Integer i = 0;
    
    //Commercial Case creation
    /*Map<Integer,Case> mapCommCaseToCreate = new Map<Integer,Case>();
    List<Case> cases= [select id,casenumber,street__c,city__c,country_picklist__c,postalcode__c,Opportunity__c,
                  Install_Cost_Quote_2__c,Install_Cost_Quote__c,Install_Hours_2__c,Install_Hours__c,
                  Scope_of_Work__c,Scope_of_Works_2__c from case where Type = 'Commercial' AND Opportunity__c IN : opptIds];
    Map<String,List<Case>> oppCommCaseMap = new Map<String,List<Case>>();
    for(Case c : cases){
        if(oppCommCaseMap.keySet().contains(c.Opportunity__c)){
            oppCommCaseMap.get(c.Opportunity__c).add(c);
        } else {
            List<Case> cl = new List<case>();
            cl.add(c);
            oppCommCaseMap.put(c.Opportunity__c, cl);
        }
    }*/
    
    List<Case> caseList= [select id,casenumber,street__c,city__c,country_picklist__c,postalcode__c,Opportunity__c,
                  Install_Cost_Quote_2__c,Install_Cost_Quote__c,Install_Hours_2__c,Install_Hours__c,
                  Scope_of_Work__c,Scope_of_Works_2__c,
                  (SELECT ID,RecordType.Name FROM WorkOrders WHERE RecordType.Name='Commercial Install' )//OR Status='Complete' OR Status='Incomplete' OR Status='Rejected')
                  from case where Type = 'Commercial' AND Opportunity__c IN : opptIds];
                  
    System.debug('caseList=>'+caseList);
    Map<String,Map<String,List<WorkOrder>>> oppCaseWoMap = new Map<String,Map<String,List<WorkOrder>>>();
    for(String str:opptIds){
        for(Case caseRec:caseList){
            for(WorkOrder wo:caseRec.WorkOrders){
                oppCaseWoMap.put(str,new Map<String,List<WorkOrder>>{caseRec.Id=>caseRec.WorkOrders});
            }
        }
    }
    
    
    
    oppMap = new Map<id,Opportunity>([select Id,Name,recordtype.name,StageName,accountid,account.type, Pricebook2Id,  
                                      account.shippingstreet,account.shippingcity,account.shippingcountry,account.shippingpostalcode,
                                      account.billingstreet,account.billingcity,account.billingcountry,account.billingpostalcode,
                                      Shipping_City__c,Shipping_Street__c,Shipping_State__c, Shipping_Country__c,
                                      (SELECT Id,product_family__c,productcode,quantity,unitprice, PricebookEntryId  FROM opportunitylineitems WHERE ProductCode = 'Mngd_Inst'),
                                      (SELECT Id FROM orders),
                                      (select contactid from opportunitycontactroles where IsPrimary = true),
                                      (SELECT Id,shippingstreet,shippingcity,shippingpostalcode,shippingcountry,billingstreet,billingcity,billingpostalcode,billingcountry FROM quotes where status = 'Accepted')
                                        from Opportunity where id IN : opptIds]);
    
    
    for(String s : opptIds){
        Opportunity opp;
        if(oppMap.keyset().contains(s)){
                    opp = oppMap.get(s);
        }
        if(opp.recordtype.name == 'Commercial' || opp.recordtype.name == 'Bid'){
            //mapCommCaseToCreate.put(i,createCommercialCase(opp.AccountId,opp.id,oppCommCaseMap.get(opp.id)));//,OpptycontactRoles));
            createCommercialCase(opp.AccountId,oppCaseWoMap.get(opp.id),oppMap.get(opp.id));
        }
    }
    //insert mapCommCaseToCreate.values();
}
}