Aress7/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>- Confirms all Scheduled Work Orders
- If a new WO is made it will untick
- Unticking on the Case manually does nothing</inlineHelpText>
        <label>Customer Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Status__c</fullName>
        <inlineHelpText>FSL Survey Work Order Status</inlineHelpText>
        <label>Survey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Customer_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/classes/TemplatePageController_Test.cls
@isTest
public class TemplatePageController_Test {
    static testMethod void testWoEnter(){
        Test.StartTest();     
        WorkType wt= new WorkType(name='Install (Domestic)',DurationType='Hours',EstimatedDuration=1);
        
        insert wt;
        
        Id caseid = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Homecharge Case').getRecordTypeId();
        case cs= new case(RecordTypeId=caseid,Status='Open',Survey_Status__c = 'Requested');
        
        insert cs;
        
        Id workOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        WorkOrder wo=new WorkOrder(RecordTypeId=workOrderId,WorkTypeId=wt.id,CaseId=cs.id,Status='Unassigned');
        wo.Customer_Confirmation__c=True;
        Insert wo;
        
        //wo.Customer_Confirmation__c=True; 
        //update wo;
        
        PageReference pageRef = Page.TemplateVfPage; // Add your VF page Name here
        pageRef.getParameters().put('woid', String.valueOf(wo.Id));
        Test.setCurrentPage(pageRef);
        
        templatepageclass tempPageTest = new templatepageclass();
        tempPageTest.WoEnter(); //call all your function here
        
        Test.StopTest();
    }
}