Aress7/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Picklist__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote_2__c</fullName>
        <label>Total Install Cost 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <label>Total Install Cost 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Hours_2__c</fullName>
        <label>Labour 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Hours__c</fullName>
        <label>Labour 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>Postcode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scope_of_Work__c</fullName>
        <label>Scope of Work 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scope_of_Works_2__c</fullName>
        <label>Scope of Works 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Status__c</fullName>
        <inlineHelpText>FSL Survey Work Order Status</inlineHelpText>
        <label>Survey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country_Picklist__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Postal_Code__c</fullName>
        <label>Billing Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote_2__c</fullName>
        <inlineHelpText>Don&apos;t forget to add margin!</inlineHelpText>
        <label>Install Quote 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <inlineHelpText>Don&apos;t forget to add margin!</inlineHelpText>
        <label>Install Quote 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Hours_2__c</fullName>
        <label>Install Hours 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Hours__c</fullName>
        <label>Install Hours 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Status_New__c</fullName>
        <label>Install Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scope_of_Work__c</fullName>
        <label>Scope of Work 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Shipping_City__c</fullName>
        <label>Shipping City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Country_Picklist__c</fullName>
        <label>Shipping Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipping_Postal_Code__c</fullName>
        <label>Shipping Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Street__c</fullName>
        <label>Shipping Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Status__c</fullName>
        <label>Survey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Commercial</fullName>
        <active>true</active>
        <businessProcess>Commercial</businessProcess>
        <label>Commercial</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <label>Install Cost Quote</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

Aress7/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Notes_about_your_order__c</fullName>
        <inlineHelpText>Notes for Helen or Finance team about your order</inlineHelpText>
        <label>Notes about your order</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Notes_about_your_order__c</fullName>
        <inlineHelpText>Notes for Supply Team</inlineHelpText>
        <label>Order Notes</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Option__c</fullName>
        <label>Survey Option</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Supply Only</fullName>
                </value>
                <value>
                    <fullName>Survey Option 1</fullName>
                </value>
                <value>
                    <fullName>Survey Option 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/classes/OpportunityTriggerHandler_Test.cls
@isTest
public class OpportunityTriggerHandler_Test{

    
    public static testmethod void test2(){
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),lastName = 'test',type = 'Prospect');
        insert acc;
        
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),Name = 'Test Opp',AccountId = acc.id,closedate = Date.today(),Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),Billing_Postal_Code__c = 'Test',Billing_Street__c = 'Test',Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),Shipping_Postal_Code__c = 'Test',Shipping_Street__c = 'Test',StageName = 'New');
        insert opp;  
        opp.Survey_Status__c='Scheduled';
        opp.StageName = 'Survey Requested';
        update opp;
        Opportunity opp1 = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Home Charge').getRecordTypeId(),Name = 'Test Opp',AccountId = acc.id,closedate = Date.today(),Billing_City__c = 'Test',Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                           Billing_Postal_Code__c = 'Test',Billing_Street__c = 'Test',Shipping_City__c = 'Test',
                                           Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),Shipping_Postal_Code__c = 'Test',Shipping_Street__c = 'Test',StageName = 'New');
        insert opp1;
        List<String> oppIdStringList=new List<String>();
        oppIdStringList.add(String.valueOf(opp1.id));
        oppIdStringList.add(String.valueOf(opp.id));

        
        Product2 pro2 = new Product2(Name='BXCD', isActive=true,ProductCode='Mngd_Inst');
        pro2.Family= 'Charging Cables';
        insert pro2;
        
        PricebookEntry pbe2 =new PricebookEntry(unitprice=0.01,Product2Id=pro2.Id,Pricebook2Id=Test.getStandardPricebookId(),isActive=true,UseStandardPrice = false);
        insert pbe2;
        
        OpportunityLineItem OPplineitem2 = new OpportunityLineItem (Quantity=2, OpportunityId=opp.Id,UnitPrice=0.01,PriceBookEntryId=pbe2.Id);
        insert OPplineitem2;
        OpportunityLineItem OPplineitem3 = new OpportunityLineItem (Quantity=2, OpportunityId=opp1.Id,UnitPrice=0.01,PriceBookEntryId=pbe2.Id);
        insert OPplineitem3;
        
        Contact con = new Contact (lastName ='con',email='test@yopmail.com');
        insert con;
        
        OpportunityContactRole orl = new OpportunityContactRole(ContactId = con.id,OpportunityId = opp.Id,IsPrimary = True);
        insert orl;
        
        Quote quttest = new Quote (Name = 'qoutetest' , OpportunityId = opp.id , Pricebook2Id = Test.getStandardPricebookId(),Survey_Option__c = 'Survey Option 1',status = 'Accepted',shippingstreet='Test',shippingcity='Test',shippingpostalcode='123654789',shippingcountry='India',billingstreet='Test',billingcity='Test',billingpostalcode='12364',billingcountry='India',Notes_about_your_order__c='Test');
        insert quttest ;
        
        Case cs = new Case(street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey');
        insert cs;
        List<Case> csl = new List<Case>();
        csl.add(cs);
        
        List<Quote> cql = new List<Quote>();
        cql.add(quttest);
        
        opp.Install_Status_New__c ='Requested';
        opp.Survey_Status__c = 'Requested';
        
        opp.StageName = 'Won';
        //opp.Install_Status_New__c ='Requested';
        //opp.Survey_Status__c = 'Requested';
        //update opp;
        WorkType wt= new WorkType(name=' Install (Domestic) & Additional Works',DurationType='Hours',EstimatedDuration=2);
        WorkType wt2= new WorkType(name= 'Install (Domestic)',DurationType='Hours',EstimatedDuration=2);
        List<WorkType> WTList=new List<WorkType>();
        WTList.add(wt);
        WTList.add(wt2);
        insert WTList;
        
        List<Id> oppIds=new List<Id>();
        oppIds.add(opp.Id);
        
        test.startTest();
        //opp.Install_Status_New__c='Scheduled';
        
        //opp.Install_Status_New__c='';
          //  update opp;
        OpportunityTriggerHandler.createInstallCase(acc.id,opp.id,opp.name,csl,cql);
        OpportunityTriggerHandler.createInstallCase(acc.id,opp.id,opp.name,null,cql);
        csl.clear();
        OpportunityTriggerHandler.createInstallCase(acc.id,opp.id,opp.name,csl,cql);
        OpportunityTriggerHandler.afterinsertOpp(oppIds);
        OpportunityTriggerHandler.syncSurveyInstallStatToStage(oppIds);
        OpportunityTriggerHandler.createCloneOnlineOppty(oppIds);
        OpportunityTriggerHandler.createOrder(opp1,Schema.SObjectType.Order.getRecordTypeInfosByName().get('Managed Installation').getRecordTypeId(),'Ready for Helen',csl,cql,csl);
        OpportunityTriggerHandler.createOrder(Opp,Schema.SObjectType.Order.getRecordTypeInfosByName().get('Managed Installation').getRecordTypeId(),'Ready for Helen',csl,cql,csl);
        OpportunityTriggerHandler.createOrder(Opp,Schema.SObjectType.Order.getRecordTypeInfosByName().get('Managed Installation').getRecordTypeId(),'Ready for Helen',null,cql,csl);
        csl.add(cs);
        opp.RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Online Payment').getRecordTypeId();
        opp.StageName='Qualified';
        //opp.Survey_Status__c='Scheduled';
        //update opp;
        update opp;
        OpportunityTriggerHandler.afterinsertOpp(oppIds);
        //OpportunityTriggerHandler.handleAfterUpdate();
        OpportunityTriggerHandler.createOrder(Opp,Schema.SObjectType.Order.getRecordTypeInfosByName().get('Managed Installation').getRecordTypeId(),'Ready for Helen',csl,cql,csl);
        OpportunityTriggerHandler.createOrder(Opp,Schema.SObjectType.Order.getRecordTypeInfosByName().get('Managed Installation').getRecordTypeId(),'Ready for Helen',csl,cql,csl);
        OpportunityTriggerHandler.handleAfterUpdate(oppIdStringList,csl);
        test.stopTest();
    }
}