Aress7/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Picklist__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>- Confirms all Scheduled Work Orders
- If a new WO is made it will untick
- Unticking on the Case manually does nothing</inlineHelpText>
        <label>Customer Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote_2__c</fullName>
        <label>Total Install Cost 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <label>Total Install Cost 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Hours_2__c</fullName>
        <label>Labour 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Hours__c</fullName>
        <label>Labour 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>Postcode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ready_to_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready to Schedule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scope_of_Work__c</fullName>
        <label>Scope of Work 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scope_of_Works_2__c</fullName>
        <label>Scope of Works 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country_Picklist__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Postal_Code__c</fullName>
        <label>Billing Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote_2__c</fullName>
        <inlineHelpText>Don&apos;t forget to add margin!</inlineHelpText>
        <label>Install Quote 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <inlineHelpText>Don&apos;t forget to add margin!</inlineHelpText>
        <label>Install Quote 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Hours_2__c</fullName>
        <label>Install Hours 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Hours__c</fullName>
        <label>Install Hours 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scope_of_Work__c</fullName>
        <label>Scope of Work 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Shipping_City__c</fullName>
        <label>Shipping City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Country_Picklist__c</fullName>
        <label>Shipping Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipping_Postal_Code__c</fullName>
        <label>Shipping Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Street__c</fullName>
        <label>Shipping Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Commercial</fullName>
        <active>true</active>
        <businessProcess>Commercial</businessProcess>
        <label>Commercial</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Customer_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_SA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is checked if the service appointment is Main Service Appointment</description>
        <label>Main SA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Case__r.Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Customer_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Case.Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Groundworks</fullName>
        <active>true</active>
        <label>Groundworks</label>
    </recordTypes>
    <recordTypes>
        <fullName>Survey</fullName>
        <active>true</active>
        <label>Survey</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/objects/WorkType.object
<CustomObject>
    <fields>
        <fullName>Appointment_Start_Offset__c</fullName>
        <description>In Minutes</description>
        <label>Appointment Start Offset</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/classes/SeriveAppointmentTriggerTest.cls
@istest
public class SeriveAppointmentTriggerTest {
    
    
    public static testmethod void test1(){    
        
        Id hcinstallWORecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
                                  lastName = 'test',type = 'Prospect');
        insert acc;
        worktype wt4 =new worktype();
        wt4.Name='Install (Domestic) & Additional Works';
        wt4.EstimatedDuration=4.0;
        wt4.DurationType='hours';
        wt4.Appointment_Start_Offset__c=20;
        insert wt4;
        
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
                                          Name = 'Test Opp',
                                          AccountId = acc.id,
                                          closedate = Date.today(),
                                          Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Billing_Postal_Code__c = 'Test',
                                          Billing_Street__c = 'Test',
                                          Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Shipping_Postal_Code__c = 'Test',
                                          Shipping_Street__c = 'Test',
                                          StageName = 'New');
        insert opp;     
        
        Case cs = new Case( AccountId = acc.id,street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
                           Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
                           Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',Ready_to_Schedule__c = true);
        insert cs;
        
        worktype wt1 =new worktype();
        wt1.Name='Install (Domestic)';
        wt1.EstimatedDuration=4.0;
        wt1.DurationType='hours';
        wt1.Appointment_Start_Offset__c=20;
        insert wt1;
        
        WorkOrder wo1= new WorkOrder();
        wo1.WorkTypeId=wt1.Id;
        wo1.AccountId=acc.Id;
        wo1.CaseId=cs.Id;
        wo1.Status='Unassigned';
        insert wo1;
        worktype wt2 =new worktype();
        wt2.Name='Additional Works (Domestic)';
        wt2.EstimatedDuration=4.0;
        wt2.DurationType='hours';
        insert wt2;
        worktype wt3 =new worktype();
        wt3.Name='Install (Domestic) & Additional Works';
        wt3.EstimatedDuration=4.0;
        wt3.DurationType='hours';
        insert wt3;
        
        ServiceAppointment sa = new ServiceAppointment();
        sa.EarliestStartTime=System.today();
        sa.DueDate=System.today()+1;
        sa.Status='Scheduled';
        sa.SchedStartTime=System.today();
        sa.SchedEndTime=System.today()+1;
        sa.ParentRecordId=wo1.id;
        sa.ArrivalWindowStartTime=System.today();
        sa.ArrivalWindowEndTime=System.today()+1;
        insert sa;
        test.startTest();
        // sa.Customer_Confirmation__c=true;
        //   update sa;
        delete sa;
        Test.setMock(HttpCalloutMock.class, new OtMockHttpResponseGenerator());
        test.stopTest();
        //   delete sa;
    }
    
    public static testmethod void test2(){    
        
        
        Id hcinstallWORecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        // WorkType wtInstallDom =[SELECT Id, name from WorkType where name='Install (Domestic)'];
        
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
                                  lastName = 'test',type = 'Prospect');
        insert acc;
        worktype wt4 =new worktype();
        wt4.Name='Install (Domestic) & Additional Works';
        wt4.EstimatedDuration=4.0;
        wt4.DurationType='hours';
        wt4.Appointment_Start_Offset__c=20;
        insert wt4;
        
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
                                          Name = 'Test Opp',
                                          AccountId = acc.id,
                                          closedate = Date.today(),
                                          Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Billing_Postal_Code__c = 'Test',
                                          Billing_Street__c = 'Test',
                                          Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Shipping_Postal_Code__c = 'Test',
                                          Shipping_Street__c = 'Test',
                                          StageName = 'New');
        insert opp;     
        
        Case cs = new Case( AccountId = acc.id,street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
                           Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
                           Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',Ready_to_Schedule__c = true);
        insert cs;
        
        worktype wt1 =new worktype();
        wt1.Name='Install (Domestic)';
        wt1.EstimatedDuration=4.0;
        wt1.DurationType='hours';
        wt1.Appointment_Start_Offset__c=20;
        insert wt1;
         worktype wt2 =new worktype();
        wt2.Name='Groundworks (Domestic)';
        wt2.EstimatedDuration=4.0;
        wt2.DurationType='hours';
        wt2.Appointment_Start_Offset__c=20;
        insert wt2;
        WorkOrder wo1= new WorkOrder();
        wo1.WorkTypeId=wt1.Id;
        wo1.AccountId=acc.Id;
        wo1.CaseId=cs.Id;
        wo1.Status='Unassigned';
        insert wo1;
         WorkOrder wo2= new WorkOrder();
        wo2.WorkTypeId=wt2.Id;
        wo2.AccountId=acc.Id;
        wo2.CaseId=cs.Id;
        wo2.Status='Unassigned';
        insert wo2;

        worktype wt3 =new worktype();
        wt3.Name='Install (Domestic) & Additional Works';
        wt3.EstimatedDuration=4.0;
        wt3.DurationType='hours';
        insert wt3;
       
        ServiceAppointment sa = new ServiceAppointment();
        sa.EarliestStartTime=System.today();
        sa.DueDate=System.today()+1;
        sa.Status='Completed';
        sa.SchedStartTime=System.today();
        sa.SchedEndTime=System.today()+1;
        sa.ParentRecordId=wo1.id;
        sa.ArrivalWindowStartTime=System.today();
        sa.ArrivalWindowEndTime=System.today()+1;
        
        insert sa;
        
        // update sa;
        
        ServiceAppointment sa1 = new ServiceAppointment();
        sa1.EarliestStartTime=System.today();
        sa1.DueDate=System.today()+1;
        sa1.Status='Unassigned';
        sa1.SchedStartTime=System.today();
        sa1.SchedEndTime=System.today()+1;
        sa1.ParentRecordId=wo1.id;
        sa1.ArrivalWindowStartTime=System.today();
        sa1.ArrivalWindowEndTime=System.today()+1;
        
        insert sa1;
        

         test.startTest();
		DateTime dt = DateTime.newInstance(2018, 7, 09, 7, 3, 3);
        sa1.SchedStartTime=dt;
        sa1.SchedEndTime=dt.addminutes(600);
        update sa1;
        
        sa1.SchedStartTime=dt.addminutes(180);
   //     sa1.Main_SA__c=true;
        update sa1;
                sa1.SchedStartTime=dt.addminutes(540);
        update sa1;

        test.stopTest();
        
    }
    
    public static testmethod void test3(){
         Id hcinstallWORecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        // WorkType wtInstallDom =[SELECT Id, name from WorkType where name='Install (Domestic)'];
        
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
                                  lastName = 'test',type = 'Prospect');
        insert acc;
        worktype wt4 =new worktype();
        wt4.Name='Install (Domestic) & Additional Works';
        wt4.EstimatedDuration=4.0;
        wt4.DurationType='hours';
        wt4.Appointment_Start_Offset__c=20;
        insert wt4;
        
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
                                          Name = 'Test Opp',
                                          AccountId = acc.id,
                                          closedate = Date.today(),
                                          Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Billing_Postal_Code__c = 'Test',
                                          Billing_Street__c = 'Test',
                                          Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Shipping_Postal_Code__c = 'Test',
                                          Shipping_Street__c = 'Test',
                                          StageName = 'New');
        insert opp;     
        
        Case cs = new Case( AccountId = acc.id,street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
                           Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
                           Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',Ready_to_Schedule__c = true);
        insert cs;
        
        worktype wt1 =new worktype();
        wt1.Name='Groundworks (Domestic)';
        wt1.EstimatedDuration=4.0;
        wt1.DurationType='hours';
        wt1.Appointment_Start_Offset__c=20;
        insert wt1;

        WorkOrder wo1= new WorkOrder();
        wo1.WorkTypeId=wt1.Id;
        wo1.AccountId=acc.Id;
        wo1.CaseId=cs.Id;
        wo1.Status='Unassigned';
        insert wo1;
    /*     WorkOrder wo2= new WorkOrder();
        wo2.WorkTypeId=wt2.Id;
        wo2.AccountId=acc.Id;
        wo2.CaseId=cs.Id;
        wo2.Status='Unassigned';
        insert wo2;*/

       
        ServiceAppointment sa = new ServiceAppointment();
        sa.EarliestStartTime=System.today();
        sa.DueDate=System.today()+1;
        sa.Status='Unassigned';
        sa.SchedStartTime=System.today();
        sa.SchedEndTime=System.today()+1;
        sa.ParentRecordId=wo1.id;
        sa.ArrivalWindowStartTime=System.today();
        sa.ArrivalWindowEndTime=System.today()+1;
        
        insert sa;
        
        // update sa;
        
    /*    ServiceAppointment sa1 = new ServiceAppointment();
        sa1.EarliestStartTime=System.today();
        sa1.DueDate=System.today()+1;
        sa1.Status='Unassigned';
        sa1.SchedStartTime=System.today();
        sa1.SchedEndTime=System.today()+1;
        sa1.ParentRecordId=wo1.id;
        sa1.ArrivalWindowStartTime=System.today();
        sa1.ArrivalWindowEndTime=System.today()+1;
        
        insert sa1;
        
        ServiceAppointment sa2 = new ServiceAppointment();
        sa2.EarliestStartTime=System.today();
        sa2.DueDate=System.today()+1;
        sa2.Status='Unassigned';
        sa2.SchedStartTime=System.today();
        sa2.SchedEndTime=System.today()+1;
        sa2.ParentRecordId=wo2.id;
        sa2.ArrivalWindowStartTime=System.today();
        sa2.ArrivalWindowEndTime=System.today()+1;
        
        insert sa2;*/
        
        
         test.startTest();
		DateTime dt = DateTime.newInstance(2018, 7, 09, 7, 3, 3);
          sa.SchedStartTime=dt;
        sa.SchedEndTime=dt.addminutes(600);
        update sa;
        delete sa;
        
        
        test.stopTest();
        
    } 
    /* public static testmethod void test5(){    

Id hcinstallWORecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
// WorkType wtInstallDom =[SELECT Id, name from WorkType where name='Install (Domestic)'];

Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
lastName = 'test',type = 'Prospect');
insert acc;
worktype wt4 =new worktype();
wt4.Name='Install (Domestic) & Additional Works';
wt4.EstimatedDuration=4.0;
wt4.DurationType='hours';
wt4.Appointment_Start_Offset__c=20;
insert wt4;

Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
Name = 'Test Opp',
AccountId = acc.id,
closedate = Date.today(),
Billing_City__c = 'Test',
Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
Billing_Postal_Code__c = 'Test',
Billing_Street__c = 'Test',
Shipping_City__c = 'Test',
Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
Shipping_Postal_Code__c = 'Test',
Shipping_Street__c = 'Test',
StageName = 'New');
insert opp;     

Case cs = new Case( AccountId = acc.id,street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey');
insert cs;

worktype wt1 =new worktype();
wt1.Name='Install (Domestic)';
wt1.EstimatedDuration=4.0;
wt1.DurationType='hours';
wt1.Appointment_Start_Offset__c=20;
insert wt1;

WorkOrder wo1= new WorkOrder();
wo1.WorkTypeId=wt1.Id;
wo1.AccountId=acc.Id;
wo1.CaseId=cs.Id;
wo1.Status='Unassigned';
insert wo1;

worktype wt2 =new worktype();
wt2.Name='Additional Works (Domestic)';
wt2.EstimatedDuration=4.0;
wt2.DurationType='hours';
insert wt2;
worktype wt3 =new worktype();
wt3.Name='Install (Domestic) & Additional Works';
wt3.EstimatedDuration=4.0;
wt3.DurationType='hours';
insert wt3;

ServiceAppointment sa = new ServiceAppointment();
sa.EarliestStartTime=System.today();
sa.DueDate=System.today()+1;
sa.Status='Completed';
sa.SchedStartTime=System.today();
sa.SchedEndTime=System.today()+1;
sa.ParentRecordId=wo1.id;
sa.ArrivalWindowStartTime=System.today();
sa.ArrivalWindowEndTime=System.today()+1;

insert sa;

update sa;
//   delete sa;

}*/
    
}