Aress7/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Equipment_Cost__c</fullName>
        <label>Equipment Cost</label>
        <summarizedField>Case_Equipment__c.Total_Cost__c</summarizedField>
        <summaryForeignKey>Case_Equipment__c.Case__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <label>Total Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/Case_Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Case_Equipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Cost Tracking Items</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Case Equipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Tracking Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Equipment_Cost__c</fullName>
        <label>Equipment Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/classes/CaseEquipmentTriggerHandler.cls
public class CaseEquipmentTriggerHandler {
    public static void handleAfterUpdate(List<Case_Equipment__c> caseEquipmentListNew){
        List<Opportunity> listOpportunity = new List<Opportunity>();
        Set<Id> caseId = new Set<Id>();
        for(Case_Equipment__c ce : caseEquipmentListNew){
           caseId.add(ce.Case__c);
        }
        
        for(Case c : [select Id,Opportunity__c,(select Total_Cost__c from Case_Equipments__r) from Case where id IN : caseId and Opportunity__c!= null]){
            Double totalcost=0.0;
            for(Case_Equipment__c ce : c.Case_Equipments__r)
            {
                if(ce.Total_Cost__c != null)
                	totalcost += ce.Total_Cost__c ;
                else
                    totalcost += 0;
            }
            Opportunity opp = new Opportunity(Id=c.Opportunity__c , Equipment_Cost__c = totalcost);
            listOpportunity.add(opp);
        }
        
        update listOpportunity;         
    }
}