Aress7/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Survey_Status__c</fullName>
        <inlineHelpText>FSL Survey Work Order Status</inlineHelpText>
        <label>Survey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Missing_Comment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If feed item is created on WO without any comment.</description>
        <label>Missing Comment</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/classes/NewFeedItemTrigger_Test.cls
@isTest
public class NewFeedItemTrigger_Test {
    static testMethod void testFeed(){
        
        
        AvoidRecursion.isFirstRun();
        AvoidRecursion.isFirstRun1();
        AvoidRecursion.isFirstRun2();
        AvoidRecursion.isFirstRun3();
        
        
        
        
        Test.StartTest();  
        list<WorkType> wtlist=new list <WorkType>();
        WorkType wt= new WorkType(name='Install (Domestic)',DurationType='Hours',EstimatedDuration=1);
        wtList.add(wt);
                worktype wt3 =new worktype(Name='Install (Domestic) & Additional Works',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt3);
        insert wtlist;
        
        Id caseid = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Homecharge Case').getRecordTypeId();
        case cs= new case(RecordTypeId=caseid,Status='Open',Survey_Status__c = 'Requested');
        
        insert cs;
        
        Id workOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        WorkOrder wo=new WorkOrder(RecordTypeId=workOrderId,WorkTypeId=wt.id,CaseId=cs.id,Status='Unassigned');
        wo.Missing_Comment__c=true;
        Insert wo;
        
        FeedItem feed = new FeedItem (ParentId = wo.Id,Body = 'Hello');
        
        insert feed;
        Delete feed;
        
        update wo;
        
        Test.StopTest();
    }
}