Aress7/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Picklist__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>- Confirms all Scheduled Work Orders
- If a new WO is made it will untick
- Unticking on the Case manually does nothing</inlineHelpText>
        <label>Customer Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote_2__c</fullName>
        <label>Total Install Cost 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <label>Total Install Cost 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Hours_2__c</fullName>
        <label>Labour 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Hours__c</fullName>
        <label>Labour 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OLEV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OLEV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_Duration__c</fullName>
        <label>Planned Duration (PPEs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>Postcode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <label>Project Manager</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amy Lambourne</fullName>
                </value>
                <value>
                    <fullName>Arne Nikolaus</fullName>
                </value>
                <value>
                    <fullName>Martin Miles</fullName>
                </value>
                <value>
                    <fullName>Richard Wise</fullName>
                </value>
                <value>
                    <fullName>Shauna Black</fullName>
                </value>
                <value>
                    <fullName>Bradley Turk</fullName>
                </value>
                <value>
                    <fullName>Joshua Doyle-Tanner</fullName>
                </value>
                <value>
                    <fullName>Kostas Papadakis</fullName>
                </value>
                <value>
                    <fullName>Alex McKinney</fullName>
                </value>
                <value>
                    <fullName>Stuart Clark</fullName>
                </value>
                <value>
                    <fullName>Richard Lindop</fullName>
                </value>
                <value>
                    <fullName>James Farrier</fullName>
                </value>
                <value>
                    <fullName>Sam Biggs</fullName>
                </value>
                <value>
                    <fullName>Richard King</fullName>
                </value>
                <value>
                    <fullName>Jagdish Nikam</fullName>
                </value>
                <value>
                    <fullName>Stephen Kellett</fullName>
                </value>
                <value>
                    <fullName>Christos Polydoros</fullName>
                </value>
                <value>
                    <fullName>Bryan Saignasith</fullName>
                </value>
                <value>
                    <fullName>Matt Preston</fullName>
                </value>
                <value>
                    <fullName>Cameron Mclean</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ready_to_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready to Schedule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scope_of_Work__c</fullName>
        <label>Scope of Work 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scope_of_Works_2__c</fullName>
        <label>Scope of Works 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timesheet_Duration__c</fullName>
        <label>Timesheet Duration (PPEs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <label>UUID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_PSL_PG_Number__c</fullName>
        <label>Unit PSL/PG Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/FSL_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Work_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Type</label>
        <referenceTo>WorkType</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FSL Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FSL Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country_Picklist__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Postal_Code__c</fullName>
        <label>Billing Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote_2__c</fullName>
        <inlineHelpText>Don&apos;t forget to add margin!</inlineHelpText>
        <label>Install Quote 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <inlineHelpText>Don&apos;t forget to add margin!</inlineHelpText>
        <label>Install Quote 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Install_Hours_2__c</fullName>
        <label>Install Hours 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Hours__c</fullName>
        <label>Install Hours 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <label>Project Manager</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scope_of_Work__c</fullName>
        <label>Scope of Work 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Shipping_City__c</fullName>
        <label>Shipping City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Country_Picklist__c</fullName>
        <label>Shipping Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipping_Postal_Code__c</fullName>
        <label>Shipping Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Street__c</fullName>
        <label>Shipping Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Commercial</fullName>
        <active>true</active>
        <businessProcess>Commercial</businessProcess>
        <label>Commercial</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Install_Cost_Quote__c</fullName>
        <label>Install Cost Quote</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

Aress7/src/objects/ProductRequired.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Products Required</relationshipLabel>
        <relationshipName>Products_Required</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WO_OppLineItem_Id__c</fullName>
        <externalId>true</externalId>
        <label>WO OppLineItem Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Customer_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_SA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is checked if the service appointment is Main Service Appointment</description>
        <label>Main SA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Case__r.Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <formula>text( Case__r.Project_Manager__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Type__c</fullName>
        <label>Work Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/objects/Work_Order_Task__c.object
<CustomObject>
    <fields>
        <fullName>Signee_Name__c</fullName>
        <label>Signee Name (If not customer)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signee_Relationship__c</fullName>
        <label>Signee Relationship (If not customer)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>FSL_Tasks__c</referenceTo>
        <relationshipLabel>Work Order Tasks</relationshipLabel>
        <relationshipName>Work_Order_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_PSL_PG_number__c</fullName>
        <label>Unit PSL/PG number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Work Order Tasks</relationshipLabel>
        <relationshipName>Work_Order_Tasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Order Task</label>
    <nameField>
        <displayFormat>WOT-{00000}</displayFormat>
        <label>Work Order Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Customer_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSFUser__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSFUser</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSiteUser__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSiteUser</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OLEV__c</fullName>
        <formula>Case.OLEV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OLEV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Case.Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planned_Duration__c</fullName>
        <description>Sum of all Duration fields from child SAs</description>
        <label>Planned Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <formula>TEXT(Case.Project_Manager__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timesheet_Duration__c</fullName>
        <description>Sum of all Timesheet Duration fields from child SAs</description>
        <label>Timesheet Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <formula>Case.UUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UUID</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Groundworks</fullName>
        <active>true</active>
        <label>Groundworks</label>
    </recordTypes>
    <recordTypes>
        <fullName>Maintenance</fullName>
        <active>true</active>
        <label>Maintenance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Survey</fullName>
        <active>true</active>
        <label>Survey</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/classes/WorkOrderTriggerTest.cls
@isTest
public class WorkOrderTriggerTest {
    
    public static testmethod void test01(){
        checkRecursive.skip_install_statuscheck_whencasecreated = true;
        Set<Id> WOId = new Set<Id>();
        Set<Id> OppId = new Set<Id>();
        
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
                                  lastName = 'test',type = 'Prospect');
        insert acc;
        Account acc2 = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId(),
                                   Name = 'test',type = 'Prospect');
        insert acc2;
        worktype wt1 =new worktype(Name='Install (Commercial)',EstimatedDuration=4.0,DurationType='hours');
        insert wt1;
        worktype wt11 =new worktype(Name='Install (Domestic) & Additional Works',EstimatedDuration=4.0,DurationType='hours');
        insert wt11;
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
                                          Name = 'Test Opp',
                                          AccountId = acc.id,
                                          closedate = Date.today(),
                                          Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Billing_Postal_Code__c = 'Test',
                                          Billing_Street__c = 'Test',
                                          Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Shipping_Postal_Code__c = 'Test',
                                          Shipping_Street__c = 'Test',
                                          StageName = 'New');
        insert opp;     
        
        Case cs = new Case(accountid=acc2.id,street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
                           Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
                           Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',UUID__c='1223456',Ready_to_Schedule__c = true);
        cs.Project_Manager__c='Jagdish Nikam';
        cs.OLEV__c=true;
        insert cs;
       
List<WorkOrder> workOrderList = new List<WorkOrder>();
List<WorkOrder> workOrderListForUpdate = new List<WorkOrder>();
Id hcInstallWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Commercial Install').getRecordTypeId();
        WorkOrder wo1= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        wo1.Planned_Duration__c=10;
        wo1.Timesheet_Duration__c=10;
        workOrderList.add(wo1);
        Id hcInstallWorkOrderIddom = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
		WorkOrder wo11= new WorkOrder(RecordtypeId = hcInstallWorkOrderIddom,WorkTypeId=wt11.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        wo11.Planned_Duration__c=10;
        wo11.Timesheet_Duration__c=10;
        workOrderList.add(wo11);
        insert workOrderList;
		wo1.Timesheet_Duration__c=15;
        update wo1;
        wo11.Status='Scheduled';
       // wo11.Customer_Confirmation__c=True;        
        update wo11;

        Test.startTest();
        wo11.Customer_Confirmation__c=True;        
        update wo11;
        Test.setMock(HttpCalloutMock.class, new OtMockHttpResponseGenerator());
        Test.stopTest();
}
    
    public static testmethod void test02(){
                checkRecursive.skip_install_statuscheck_whencasecreated = true;
        Set<Id> WOId = new Set<Id>();
        Set<Id> OppId = new Set<Id>();
        List<worktype> wtList=new List<WorkType>();
        worktype wt1 =new worktype(Name='Install (Domestic)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt1);
        worktype wt2 =new worktype(Name='Additional Works (Domestic)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt2);
        worktype wt3 =new worktype(Name='Install (Domestic) & Additional Works',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt3);
        insert wtList;
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
                                  lastName = 'test',type = 'Prospect');
        insert acc;
        
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
                                          Name = 'Test Opp',
                                          AccountId = acc.id,
                                          closedate = Date.today(),
                                          Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Billing_Postal_Code__c = 'Test',
                                          Billing_Street__c = 'Test',
                                          Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Shipping_Postal_Code__c = 'Test',
                                          Shipping_Street__c = 'Test',
                                          StageName = 'New');
        insert opp;     
        
        Case cs = new Case(accountid=acc.id,street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
                           Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
                           Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',UUID__c='1223456',Ready_to_Schedule__c = true);
        insert cs;
        
        
        
        Id hcInstallWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        List<WorkOrder> woList=new List<WorkOrder>();
        WorkOrder wo1= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSFUser__c=True,Customer_Confirmation__c=True);
        woList.add(wo1) ;
        WorkOrder wo2= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSFUser__c=True,Customer_Confirmation__c=True);
        woList.add(wo2) ;
        insert woList;
        
        
        
        List<WorkOrder> woListToUpdate=new List<WorkOrder>();
        wo1.Status='Rejected';
        woListToUpdate.add(wo1);
        wo2.Status='On Hold';
        woListToUpdate.add(wo2);
        update woListToUpdate;
        
        
        WOId.add(wo1.Id);
        WOId.add(wo2.Id);
        //WOId.add(wo2.Id);
        
        OppId.add(opp.Id);
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Product2 prod = new Product2(
            Name = 'Product X',
            ProductCode = 'Pro-X',
            isActive = true
        );
        insert prod;
        
        //Create your pricebook entry
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        
        //create your opportunity line item.  This assumes you already have an opportunity created, called opp
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = opp.Id;
        oli.Quantity = 5;
        oli.PricebookEntryId = pbEntry.Id;
        oli.Product2Id=prod.id;
        oli.OpportunityId=opp.Id;
        // oli.TotalPrice=Quantity * pbEntry.UnitPrice;
        oli.TotalPrice=oli.Quantity * pbEntry.UnitPrice;
        insert oli;
        
        List<ProductRequired> Prodlst = new List<ProductRequired>(); 
        
        ProductRequired pr = new ProductRequired();
        pr.ParentRecordId = wo1.Id;
        pr.Product2Id = oli.Product2Id;
        pr.Opportunity__c = oli.OpportunityId;
        pr.QuantityRequired = oli.Quantity;
        system.debug('pr.QuantityRequired' + pr.QuantityRequired);
        pr.WO_OppLineItem_Id__c = oli.id;
        Prodlst.add(pr);
        
        Map<Id,WorkOrder> WOMap = new Map<Id,WorkOrder>();
        WOMap.put(wo1.Id, wo1);
        
        Map<Id, OpportunityLineItem> oliMap = new Map<Id, OpportunityLineItem>();
        oliMap.put(oli.Id, oli);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new OtMockHttpResponseGenerator());
        Test.stopTest();
    }
    /*public static testmethod void test03(){
Set<Id> WOId = new Set<Id>();
Set<Id> OppId = new Set<Id>();

Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
lastName = 'test',type = 'Prospect');
insert acc;

Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
Name = 'Test Opp',
AccountId = acc.id,
closedate = Date.today(),
Billing_City__c = 'Test',
Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
Billing_Postal_Code__c = 'Test',
Billing_Street__c = 'Test',
Shipping_City__c = 'Test',
Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
Shipping_Postal_Code__c = 'Test',
Shipping_Street__c = 'Test',
StageName = 'New');
insert opp;     

Case cs = new Case(street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',UUID__c='1223456');
cs.OLEV__c=true;
insert cs;

List<worktype> wtList=new List<WorkType>();
worktype wt1 =new worktype(Name='Install (Domestic)',EstimatedDuration=4.0,DurationType='hours');
wtList.add(wt1);
worktype wt2 =new worktype(Name='Additional Works (Domestic)',EstimatedDuration=4.0,DurationType='hours');
wtList.add(wt2);
worktype wt3 =new worktype(Name='Install (Domestic) & Additional Works',EstimatedDuration=4.0,DurationType='hours');
wtList.add(wt3);
insert wtList;

Id hcInstallWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
List<WorkOrder> woList=new List<WorkOrder>();
WorkOrder wo1= new WorkOrder(Status='Active',RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSFUser__c=True,Customer_Confirmation__c=True);
woList.add(wo1) ;
//WorkOrder wo2= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id);
//woList.add(wo2) ;
insert woList;

ServiceAppointment sa = new ServiceAppointment();
sa.EarliestStartTime=System.today();
sa.DueDate=System.today()+1;
sa.Status='Completed';
sa.SchedStartTime=System.today();
sa.SchedEndTime=System.today()+1;
sa.ParentRecordId=wo1.id;
sa.ArrivalWindowStartTime=System.today();
sa.ArrivalWindowEndTime=System.today()+1;
sa.Main_SA__c=true;
//sa.WorkTypeId = wt1.Id;
insert sa;



List<FSL_Tasks__c> fslTaskList = new List<FSL_Tasks__c>();
FSL_Tasks__c fslTask = new FSL_Tasks__c(Name = 'Unit PSL/PG Number',Work_Type__c =wt1.Id);
FSL_Tasks__c fslTask1 = new FSL_Tasks__c(Name = 'Annex D Form',Work_Type__c =wt1.Id);
fslTaskList.add(fslTask);
fslTaskList.add(fslTask1);
Insert fslTaskList;

List<Work_Order_Task__c> wotaskList1= new List<Work_Order_Task__c>();
Work_Order_Task__c wot = new Work_Order_Task__c(Work_Order__c=wo1.Id, Signee_Name__c='testSignee', Signee_Relationship__c='TestRelationship', Unit_PSL_PG_number__c='testPgNo', Annex_D_Form__c='testForm1', Task__c=fslTask.Id);
wot.Status__c='Completed';
Work_Order_Task__c wot1 = new Work_Order_Task__c(Work_Order__c=wo1.Id, Signee_Name__c='testSignee', Signee_Relationship__c='TestRelationship1', Unit_PSL_PG_number__c='testPgNo1', Annex_D_Form__c='testForm2', Task__c=fslTask1.Id);
wot1.Status__c='Completed';
wotaskList1.add(wot);
wotaskList1.add(wot1);
Insert wotaskList1;


List<WorkOrder> woListToUpdate=new List<WorkOrder>();
wo1.Status='Completed';
//update wo1;
woListToUpdate.add(wo1);
//wo2.Status='Confirmed';
//woListToUpdate.add(wo2);
//update woListToUpdate;

List<Work_Order_Task__c> wotaskList= new List<Work_Order_Task__c>([SELECT Work_Order__c, Status__c, Id, Task__c FROM Work_Order_Task__c where Work_Order__c=:wo1.Id]);
// for(Work_Order_Task__c wot : wotaskList){
//     wot.Status__c='Completed';

// }
//  delete wotaskList;
List<ServiceAppointment> saList= new List<ServiceAppointment>([SELECT Id, ParentRecordId, Status FROM ServiceAppointment where ParentRecordId=:wo1.Id]);
// for(ServiceAppointment sa: saList){
//     sa.Status='Completed';
// }
delete saList;        




WOId.add(wo1.Id);
//WOId.add(wo2.Id);
//WOId.add(wo2.Id);

OppId.add(opp.Id);

Id pricebookId = Test.getStandardPricebookId();

Product2 prod = new Product2(
Name = 'Product X',
ProductCode = 'Pro-X',
isActive = true
);
insert prod;

//Create your pricebook entry
PricebookEntry pbEntry = new PricebookEntry(
Pricebook2Id = pricebookId,
Product2Id = prod.Id,
UnitPrice = 100.00,
IsActive = true
);
insert pbEntry;

//create your opportunity line item.  This assumes you already have an opportunity created, called opp
OpportunityLineItem oli = new OpportunityLineItem();
oli.OpportunityId = opp.Id;
oli.Quantity = 5;
oli.PricebookEntryId = pbEntry.Id;
oli.Product2Id=prod.id;
oli.OpportunityId=opp.Id;
// oli.TotalPrice=Quantity * pbEntry.UnitPrice;
oli.TotalPrice=oli.Quantity * pbEntry.UnitPrice;
insert oli;

List<ProductRequired> Prodlst = new List<ProductRequired>(); 

ProductRequired pr = new ProductRequired();
pr.ParentRecordId = wo1.Id;
pr.Product2Id = oli.Product2Id;
pr.Opportunity__c = oli.OpportunityId;
pr.QuantityRequired = oli.Quantity;
system.debug('pr.QuantityRequired' + pr.QuantityRequired);
pr.WO_OppLineItem_Id__c = oli.id;
Prodlst.add(pr);

Map<Id,WorkOrder> WOMap = new Map<Id,WorkOrder>();
WOMap.put(wo1.Id, wo1);

Map<Id, OpportunityLineItem> oliMap = new Map<Id, OpportunityLineItem>();
oliMap.put(oli.Id, oli);
Test.startTest();
//Test.setMock(HttpCalloutMock.class, new OtMockHttpResponseGenerator());
Test.stopTest();
}*/
    public static testMethod void afterInsertTest(){
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),lastName = 'test',type = 'Prospect');
        insert acc;
        Account acc3 = new Account(lastName = 'test',type = 'Prospect');
        insert acc3;
        
        //Case
        worktype wt =new worktype(Name='Install (Domestic)',EstimatedDuration=4.0,DurationType='hours');
        insert wt;
        worktype wt11 =new worktype(Name='Install (Domestic) & Additional Works',EstimatedDuration=4.0,DurationType='hours');
        insert wt11;
        WorkOrder wo = new WorkOrder(RecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Survey').getRecordTypeId(),
                                     WorkTypeId=wt.Id,AccountId=acc3.Id);
        
    }
    
   /* public static testMethod void method5(){
        
        Set<Id> WOId = new Set<Id>();
        Set<Id> OppId = new Set<Id>();
        List<worktype> wtList=new List<WorkType>();
        worktype wt1 =new worktype(Name='Install (Domestic)',EstimatedDuration=4.0,DurationType='hours',ShouldAutoCreateSvcAppt =true);
        
        wtList.add(wt1);
        worktype wt2 =new worktype(Name='Additional Works (Domestic)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt2);
        worktype wt3 =new worktype(Name='Install (Domestic) & Additional Works',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt3);
        insert wtList;
        
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
                                  lastName = 'test',type = 'Prospect');
        insert acc;
        
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
                                          Name = 'Test Opp',
                                          AccountId = acc.id,
                                          closedate = Date.today(),
                                          Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Billing_Postal_Code__c = 'Test',
                                          Billing_Street__c = 'Test',
                                          Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Shipping_Postal_Code__c = 'Test',
                                          Shipping_Street__c = 'Test',
                                          StageName = 'New');
        insert opp;     
        
        Case cs = new Case(accountid=acc.id,street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
                           Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
                           Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',UUID__c='1223456');
        insert cs;
        
        
        Id hcInstallWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        List<WorkOrder> woList=new List<WorkOrder>();
        WorkOrder wo1= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True,IsSFUser__c=true);
        woList.add(wo1) ;
        // WorkOrder wo2= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSFUser__c=True,Customer_Confirmation__c=True);
        //  woList.add(wo2) ;
        insert woList;
        serviceAppointment sa=[SELECT ID,SchedStartTime,SchedEndTime,ParentRecordId,ActualEndTime,Main_SA__c,Technician__c,Installer_Id_c__c FROM ServiceAppointment WHERE Main_SA__c=True and ParentRecordId=:wo1.id limit 1];
        sa.SchedStartTime=system.now();
        sa.SchedEndTime=system.now()+1;
        update sa;
        Test.startTest();
        wo1.Status='Scheduled';
        update wo1;
        wo1.Customer_Confirmation__c=true;
        update wo1;
        wo1.Customer_Confirmation__c=false;
        update wo1;
        wo1.Customer_Confirmation__c=true;
        update wo1;
        Test.setMock(HttpCalloutMock.class, new OtMockHttpResponseGenerator());
        Test.stopTest();
        
    }    */
    
    public static testMethod void method6(){
        
        Set<Id> WOId = new Set<Id>();
        Set<Id> OppId = new Set<Id>();
        List<worktype> wtList=new List<WorkType>();
        worktype wt1 =new worktype(Name='Install (Domestic)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt1);
        worktype wt2 =new worktype(Name='Groundworks (Commercial)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt2);
        worktype wt3 =new worktype(Name='Maintenance (Domestic)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt3);
        worktype wt4 =new worktype(Name='Survey (Commercial)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt4);
        worktype wt11 =new worktype(Name='Install (Domestic) & Additional Works',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt11);
        insert wtList;
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
                                  lastName = 'test',type = 'Prospect');
        insert acc;
        
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
                                          Name = 'Test Opp',
                                          AccountId = acc.id,
                                          closedate = Date.today(),
                                          Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Billing_Postal_Code__c = 'Test',
                                          Billing_Street__c = 'Test',
                                          Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Shipping_Postal_Code__c = 'Test',
                                          Shipping_Street__c = 'Test',
                                          StageName = 'New');
        insert opp;     
        
        Case cs = new Case(accountid=acc.id,street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
                           Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
                           Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',UUID__c='1223456',Ready_to_Schedule__c = true);
        insert cs;
        
        
        
        Id hcInstallWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        Id groundworksWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Groundworks').getRecordTypeId();
        Id MaintainanceWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Maintenance').getRecordTypeId();
        Id SurveyWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Survey').getRecordTypeId();
        
        List<WorkOrder> woList=new List<WorkOrder>();
        WorkOrder wo1= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True,IsSFUser__c=true);
        woList.add(wo1) ;
        WorkOrder wo2= new WorkOrder(RecordtypeId = groundworksWorkOrderId,WorkTypeId=wt2.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True,IsSFUser__c=true);
        woList.add(wo2) ;
        WorkOrder wo3= new WorkOrder(RecordtypeId = MaintainanceWorkOrderId,WorkTypeId=wt3.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True,IsSFUser__c=true);
        woList.add(wo3) ;
        WorkOrder wo4= new WorkOrder(RecordtypeId = SurveyWorkOrderId,WorkTypeId=wt4.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True,IsSFUser__c=true);
        woList.add(wo4) ;
        // WorkOrder wo2= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSFUser__c=True,Customer_Confirmation__c=True);
        //  woList.add(wo2) ;
        insert woList;
        wo1.Arrival_Window_End_Time__c='11:15';
        //update wo1;
        wo2.Arrival_Window_End_Time__c='11:15';
        //update wo2;
        wo3.Arrival_Window_End_Time__c='11:15';
        //update wo3;
        wo4.Arrival_Window_End_Time__c='11:15';
        //update wo4;
        update woList;
        
    }    
    
   /* public static testmethod void test07(){
        Set<Id> WOId = new Set<Id>();
        Set<Id> OppId = new Set<Id>();
        
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
                                  lastName = 'test',type = 'Prospect');
        insert acc;
        Account acc2 = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId(),
                                   Name = 'test',type = 'Prospect');
        insert acc2;
        worktype wt1 =new worktype(Name='Install (Domestic)',EstimatedDuration=4.0,DurationType='hours',ShouldAutoCreateSvcAppt =true);
        insert wt1;

        
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
                                          Name = 'Test Opp',
                                          AccountId = acc.id,
                                          closedate = Date.today(),
                                          Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Billing_Postal_Code__c = 'Test',
                                          Billing_Street__c = 'Test',
                                          Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Shipping_Postal_Code__c = 'Test',
                                          Shipping_Street__c = 'Test',
                                          StageName = 'New');
        insert opp;     
        
        Case cs = new Case(accountid=acc2.id,street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
                           Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
                           Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',UUID__c='1223456');
        cs.OLEV__c=true;
        insert cs;
         
        List<WorkOrder> workOrderList = new List<WorkOrder>();
        List<WorkOrder> workOrderListForUpdate = new List<WorkOrder>();
        Id hcInstallWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        WorkOrder wo1= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        workOrderList.add(wo1);
        insert workOrderList;
       serviceAppointment sa1 = new ServiceAppointment();
        sa1.EarliestStartTime=System.today()+2;
        sa1.DueDate=System.today()+3;
        sa1.Status='Scheduled';
        sa1.SchedStartTime=System.today();
        sa1.SchedEndTime=System.today()+2;
        sa1.ParentRecordId=wo1.id;
        sa1.Main_SA__c=true;
        sa1.Customer_Confirmation__c=false;
        insert sa1;
        wo1.Status='Scheduled';
      //  wo1.Customer_Confirmation__c=True;
        //wo1.IsSFUser__c=True;
        //workOrderListForUpdate.add(wo1);
        update wo1;
         Test.startTest();
      wo1.Customer_Confirmation__c=True;
      update wo1;
         Test.setMock(HttpCalloutMock.class, new OtMockHttpResponseGenerator());
        Test.stopTest();
               

} */
    
    public static testmethod void test08(){
        checkRecursive.skip_install_statuscheck_whencasecreated = true;
        Set<Id> WOId = new Set<Id>();
        Set<Id> OppId = new Set<Id>();
        
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
                                  lastName = 'test',type = 'Prospect');
        insert acc;
        Account acc2 = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId(),
                                   Name = 'test',type = 'Prospect');
        insert acc2;
        List<WorkType> wtList=new List<WorkType>();
        worktype wt1 =new worktype(Name='Install (Domestic)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt1) ;
        worktype wt11 =new worktype(Name='Install (Domestic) & Additional Works',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt11) ;
        worktype wt12 =new worktype(Name='Survey (Commercial)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt12) ;
        worktype wt13 =new worktype(Name='Maintenance (Commercial)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt13) ;
        insert wtList;
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
                                          Name = 'Test Opp',
                                          AccountId = acc.id,
                                          closedate = Date.today(),
                                          Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Billing_Postal_Code__c = 'Test',
                                          Billing_Street__c = 'Test',
                                          Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Shipping_Postal_Code__c = 'Test',
                                          Shipping_Street__c = 'Test',
                                          StageName = 'New');
        insert opp;     
        
        Case cs = new Case(accountid=acc2.id,street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
                           Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
                           Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',UUID__c='1223456',Ready_to_Schedule__c = true);
        cs.OLEV__c=true;
        insert cs;
        
        List<WorkOrder> workOrderList = new List<WorkOrder>();
        List<WorkOrder> workOrderListForUpdate = new List<WorkOrder>();
        Id hcInstallWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        Id surveyWORecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Survey').getRecordTypeId();
        //  Id commWORecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Commercial Install').getRecordTypeId();
        Id maintenanceWORecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Maintenance').getRecordTypeId();
        
        WorkOrder wo1= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,Status='Active',WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        workOrderList.add(wo1);
        WorkOrder wo2= new WorkOrder(RecordtypeId = surveyWORecordTypeId,Status='Active',WorkTypeId=wt12.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        workOrderList.add(wo2);
        WorkOrder wo3= new WorkOrder(RecordtypeId = maintenanceWORecordTypeId,Status='Active',WorkTypeId=wt13.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        workOrderList.add(wo3);
        //        WorkOrder wo4= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,Status='Active',WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        //workOrderList.add(wo4);
        insert workOrderList;

        //wo1.Arrival_Window_End_Time__c=string.valueOf(System.today());
        //update wo1;
        wo2.Arrival_Window_End_Time__c=string.valueOf(System.today());
        wo3.Arrival_Window_End_Time__c=string.valueOf(System.today());
        wo1.Arrival_Window_End_Time__c=string.valueOf(System.today());
        wo1.Status='Completed';
        if(workOrderList.size()>0){
           update workOrderList;
        }
        //update wo1;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new OtMockHttpResponseGenerator());
        Test.stopTest();
}
    
    public static testmethod void test09(){
        checkRecursive.skip_install_statuscheck_whencasecreated = true;
        Set<Id> WOId = new Set<Id>();
        Set<Id> OppId = new Set<Id>();
        
        Account acc = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
                                  lastName = 'test',type = 'Prospect');
        insert acc;
        Account acc2 = new Account(recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId(),
                                   Name = 'test',type = 'Prospect');
        insert acc2;
        List<WorkType> wtList=new List<WorkType>();
        worktype wt1 =new worktype(Name='Install (Domestic)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt1) ;
        worktype wt11 =new worktype(Name='Install (Domestic) & Additional Works',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt11) ;
        worktype wt12 =new worktype(Name='Survey (Commercial)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt12) ;
        worktype wt13 =new worktype(Name='Maintenance (Commercial)',EstimatedDuration=4.0,DurationType='hours');
        wtList.add(wt13) ;
        insert wtList;
        Opportunity opp = new Opportunity(recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commercial').getRecordTypeId(),
                                          Name = 'Test Opp',
                                          AccountId = acc.id,
                                          closedate = Date.today(),
                                          Billing_City__c = 'Test',
                                          Billing_Country_Picklist__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Billing_Postal_Code__c = 'Test',
                                          Billing_Street__c = 'Test',
                                          Shipping_City__c = 'Test',
                                          Shipping_Country_PickList__c = SObjectType.Opportunity.Fields.Billing_Country_Picklist__c.PicklistValues[0].getValue(),
                                          Shipping_Postal_Code__c = 'Test',
                                          Shipping_Street__c = 'Test',
                                          StageName = 'New');
        insert opp;     
        
        Case cs = new Case(accountid=acc2.id,street__c='Test',city__c='test',country_picklist__c='India',postalcode__c='735101',Opportunity__c=opp.id,
                           Install_Cost_Quote_2__c=1000,Install_Cost_Quote__c=500,Install_Hours_2__c=200,Install_Hours__c=200,
                           Scope_of_Work__c='test',Scope_of_Works_2__c='test',type='Survey',UUID__c='1223456',Ready_to_Schedule__c = true);
        cs.OLEV__c=true;
        insert cs;
        
        List<WorkOrder> workOrderList = new List<WorkOrder>();
        List<WorkOrder> workOrderListForUpdate = new List<WorkOrder>();
        Id hcInstallWorkOrderId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Homecharge Install').getRecordTypeId();
        Id surveyWORecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Survey').getRecordTypeId();
        //  Id commWORecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Commercial Install').getRecordTypeId();
        Id maintenanceWORecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Maintenance').getRecordTypeId();
        
        WorkOrder wo1= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,Status='Active',WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        workOrderList.add(wo1);
        WorkOrder wo2= new WorkOrder(RecordtypeId = surveyWORecordTypeId,Status='Active',WorkTypeId=wt12.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        workOrderList.add(wo2);
        WorkOrder wo22= new WorkOrder(RecordtypeId = surveyWORecordTypeId,Status='Completed',WorkTypeId=wt12.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        workOrderList.add(wo22);
        WorkOrder wo3= new WorkOrder(RecordtypeId = maintenanceWORecordTypeId,Status='Active',WorkTypeId=wt13.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        workOrderList.add(wo3);
        WorkOrder wo33= new WorkOrder(RecordtypeId = maintenanceWORecordTypeId,Status='Completed',WorkTypeId=wt13.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        workOrderList.add(wo33);
        //        WorkOrder wo4= new WorkOrder(RecordtypeId = hcInstallWorkOrderId,Status='Active',WorkTypeId=wt1.Id,AccountId=acc.Id,CaseId=cs.Id,IsSiteUser__c=True);
        //workOrderList.add(wo4);
        insert workOrderList;
        
        //wo1.Arrival_Window_End_Time__c=string.valueOf(System.today());
        //update wo1;
        wo2.Arrival_Window_End_Time__c=string.valueOf(System.today());
        wo3.Arrival_Window_End_Time__c=string.valueOf(System.today());
        wo1.Arrival_Window_End_Time__c=string.valueOf(System.today());
        wo1.Status='Completed';
        if(workOrderList.size()>0){
           update workOrderList;
        }
        
        //update wo1;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new OtMockHttpResponseGenerator());
        Test.stopTest();
}
    
    
}