Aress7/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Call_Category__c</fullName>
        <label>Call Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Origin</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Homecharge</fullName>
                </value>
                <value>
                    <fullName>Support Issue</fullName>
                </value>
                <value>
                    <fullName>Support Enquiry</fullName>
                </value>
                <value>
                    <fullName>Other Dept. Enquiry</fullName>
                </value>
                <value>
                    <fullName>General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Call_Subcategory__c</fullName>
        <label>Call Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Call_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Enquiry</fullName>
                </value>
                <value>
                    <fullName>Ops Enquiry</fullName>
                </value>
                <value>
                    <fullName>App</fullName>
                </value>
                <value>
                    <fullName>Home Unit</fullName>
                </value>
                <value>
                    <fullName>Commercial Unit</fullName>
                </value>
                <value>
                    <fullName>How to use Homecharge Unit</fullName>
                </value>
                <value>
                    <fullName>How to use Commercial Unit</fullName>
                </value>
                <value>
                    <fullName>Commercial Sales</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Recruitment</fullName>
                </value>
                <value>
                    <fullName>PD/Ops</fullName>
                </value>
                <value>
                    <fullName>Charging</fullName>
                </value>
                <value>
                    <fullName>EVs</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
                <value>
                    <fullName>Sales Call</fullName>
                </value>
                <value>
                    <fullName>Failed Call</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Dealership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Aress7/src/classes/FeedBackController_Test.cls
@isTest
public class FeedBackController_Test{
    public static Case createCase(String stat){
        Case c = new Case(Origin = 'Email',Call_Category__c='N/A',Call_Subcategory__c='N/A',Type='N/A',Status=stat,Priority='Low',recordtypeid= Schema.SObjectType.Case.getRecordTypeInfosByName().get('Support Case').getRecordTypeId());
        return c;
    }
    
    private static testMethod void test1(){
        Case c =  createCase('New');
        insert c;
        
        PageReference pageRef = Page.FeedBackPage;
        pageRef.getParameters().put('csId', String.valueOf(c.Id));
        pageRef.getParameters().put('rat', 'Good');
        Test.setCurrentPage(pageRef);
        FeedBackController f = new FeedBackController();
        f.goodBtn();
        f.badBtn();
        f.doSave();
           
    }
}