Aress7/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Internal_Order__c</fullName>
        <label>Internal Order #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Send_Date__c</fullName>
        <label>Order Send Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/classes/AllOrderPageController.cls
public class AllOrderPageController {

    private final Order ord;
    public string orderID {get;set;}
    public List<Order> AllOrders {get;set;}
    public List<Order> CompletedOrders {get;set;}
    public List<Order> IncompleteOrders {get;set;}

    
    
    // The extension constructor initializes the private member
    // variable acct by using the getRecord method from the standard
    // controller.
    public AllOrderPageController() {
       
        	getAllOrdersforiPro();
      
    }

   
    public void getAllOrdersforiPro() 
    {
        AllOrders = [select id,account.name,ordernumber,status,Internal_Order__c,description,Order_Send_Date__c  from order where Order_Send_Date__c != null and (status ='Cancelled' or status ='Ready for Dispatch' or status ='Partially Dispatched')];
        
        CompletedOrders = [select id,account.name,ordernumber,status,Internal_Order__c,description,Order_Send_Date__c,CreatedDate  from order where status ='Dispatched' and CreatedDate = LAST_N_DAYS:30];
        //return ordItems;
    }
    
	
}