Aress7/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Notes_about_your_order__c</fullName>
        <inlineHelpText>Notes for Supply Team</inlineHelpText>
        <label>Order Notes</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aress7/src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Incomplete_Reason__c</fullName>
        <label>Incomplete Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Additional Works Required</fullName>
                </value>
                <value>
                    <fullName>Unsafe Working Environment</fullName>
                </value>
                <value>
                    <fullName>Customer Not Present</fullName>
                </value>
                <value>
                    <fullName>Could Not Locate Unit</fullName>
                </value>
                <value>
                    <fullName>Could Not Diagnose</fullName>
                </value>
                <value>
                    <fullName>Could Not Access Supply</fullName>
                </value>
                <value>
                    <fullName>Not Enough Time</fullName>
                </value>
                <value>
                    <fullName>Insufficient Supply</fullName>
                </value>
                <value>
                    <fullName>Insufficient Parts</fullName>
                </value>
                <value>
                    <fullName>Insufficient Tools</fullName>
                </value>
                <value>
                    <fullName>Insufficient Materials</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Sickness</fullName>
                </value>
                <value>
                    <fullName>Adverse Weather</fullName>
                </value>
                <value>
                    <fullName>Outlander Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/classes/ServiceAppointmentTriggerHandler.cls
public class ServiceAppointmentTriggerHandler {
    
     public static boolean run = true;
    
    //This method creates online payment oppty and Quotes
    public static void createOnlinePayOpptynQuote(SET<Id> woIdSet,SET<Id> caseIdSet){
        Opportunity oppRec;
        FeedItem post;
        Id opRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Online Payment').getRecordTypeId();
        List<Opportunity> OpptyList = new List<Opportunity>();
        List<Quote> quoteList = new List<Quote>();
        List<FeedItem> feedList = new List<FeedItem>();
        Map<Id, Attachment> attchmentMap= new Map<Id, Attachment>([SELECT ParentId, Name, Id,OwnerId , Body FROM Attachment where ParentId IN : woIdSet]);
        List<Attachment> attachments = new List<Attachment>();
        List<WorkOrder> woList = [SELECT ID,Status,Incomplete_Reason__c,Case.Id,Case.AccountId FROM WorkOrder WHERE ID IN:woIdSet];
        List<Case> caseList =  [SELECT ID,Account.name,AccountId FROM Case WHERE ID IN:caseIdSet];
        For(WorkOrder woRec:woList){
            for(Case caseRec:caseList){
                oppRec = new Opportunity(Name ='HC Online Payment - '+caseRec.Account.Name,RecordTypeId=opRecordTypeId,AccountId=caseRec.AccountId,CloseDate = Date.today(),StageName = 'Unassigned');
                OpptyList.add(oppRec); 
                // quoteList.add(new Quote(Name,OpportunityId=,ExpirationDate,Notes_about_your_order__c));
            }
        }
        Insert OpptyList;
        
        System.debug('OpptyList=>'+OpptyList);
        Quote qtRec = new Quote(Name =oppRec.Name, OpportunityId= oppRec.Id,ExpirationDate =Date.today() ,Notes_about_your_order__c = 'N/A');
        quoteList.add(qtRec);
        Insert quoteList;
        for(WorkOrder wo : woList){ 
            for(Case caseRec1:caseList){
                for(Opportunity opRec:OpptyList){
                    for(Attachment file : attchmentMap.values()) {
                        Attachment newFile = file.clone();
                        newFile.ParentId = opRec.Id;
                        attachments.add(newFile);
                    }
                 }
                 post = new FeedItem(ParentId = caseRec1.Id,Body = 'Add Work Required');
                 feedList.add(post);
            }
        }    
        Insert post;
        Insert attachments;
        
        //FeedItem post = new FeedItem(ParentId = ,Body = 'Add Work Required');
        //feedList.add(post);
        //Insert post;
    }

}