Aress7/src/objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Actual_Duration_Hours__c</fullName>
        <description>&quot;Actual Duration (Hours)&quot; which is formula field that converts minutes to hours from the &quot;Actual Duration (Minutes)&quot; field</description>
        <formula>ActualDuration  / 60</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Duration (Hours)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Arrival_Window_End_Time__c</fullName>
        <formula>TEXT(HOUR(TimeValue((ArrivalWindowEndTime)))
+((DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 00:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 01:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 02:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 03:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 04:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 05:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 06:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 07:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 08:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 09:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 10:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 11:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 12:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 13:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 14:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 15:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 16:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 17:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 18:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 19:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 20:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 21:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 22:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 23:00:00&quot;)) - TODAY()))
)+ &apos;:&apos;+ 
 IF(LEN(TEXT( MINUTE(TimeValue((ArrivalWindowEndTime)))))=1, &apos;00&apos;, TEXT( MINUTE(TimeValue((ArrivalWindowEndTime)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Arrival Window End (Time)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Arrival_Window_Start_Time__c</fullName>
        <formula>TEXT(HOUR(TimeValue((ArrivalWindowStartTime))) 
+((DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 00:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 01:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 02:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 03:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 04:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 05:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 06:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 07:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 08:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 09:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 10:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 11:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 12:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 13:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 14:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 15:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 16:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 17:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 18:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 19:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 20:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 21:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 22:00:00&quot;)) - TODAY()) + 
(DATEVALUE(DATETIMEVALUE(TEXT(TODAY())+&quot; 23:00:00&quot;)) - TODAY())) 
)+ &apos;:&apos;+ 
IF(LEN(TEXT( MINUTE(TimeValue((ArrivalWindowStartTime)))))=1, &apos;00&apos;, TEXT( MINUTE(TimeValue((ArrivalWindowStartTime)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Arrival Window Start (Time)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Appointment_Grade__c</fullName>
        <label>Appointment Grade</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FSL__Auto_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Schedule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Emergency__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Emergency</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__GanttColor__c</fullName>
        <label>Gantt Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL__GanttLabel__c</fullName>
        <label>Gantt Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL__InJeopardyReason__c</fullName>
        <label>In Jeopardy Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delayed Start</fullName>
                </value>
                <value>
                    <fullName>Delayed Finish</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Due Date Approaching</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL__InJeopardy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Jeopardy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__InternalSLRGeolocation__c</fullName>
        <label>Internal SLR Geolocation</label>
        <scale>6</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>FSL__IsFillInCandidate__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Fill In Candidate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__IsMultiDay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is MultiDay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__MDS_Calculated_length__c</fullName>
        <label>Multiday Work Calculated length</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FSL__MDT_Operational_Time__c</fullName>
        <label>Multiday Work Operational Time</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FSL__Pinned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pinned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Prevent_Geocoding_For_Chatter_Actions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prevent Geocoding For Chatter Actions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Related_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Service</label>
        <referenceTo>ServiceAppointment</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FSL__Same_Day__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same Day</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Same_Resource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same Resource</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Schedule_Mode__c</fullName>
        <label>Schedule Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Automatic</fullName>
                </value>
                <value>
                    <fullName>Optimization</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL__Schedule_over_lower_priority_appointment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Schedule Over Lower Priority Appointment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Scheduling_Policy_Used__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scheduling Policy Used</label>
        <referenceTo>FSL__Scheduling_Policy__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FSL__Time_Dependency__c</fullName>
        <label>Time Dependency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Same Start</fullName>
                </value>
                <value>
                    <fullName>Start After Finish</fullName>
                </value>
                <value>
                    <fullName>Finish Before Start</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL__UpdatedByOptimization__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UpdatedByOptimization</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Virtual_Service_For_Chatter_Action__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Virtual Service For Chatter Action (SLR)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Incomplete_Reason_Other__c</fullName>
        <label>Incomplete Reason (Other)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Incomplete_Reason__c</fullName>
        <label>Incomplete Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Additional Works Required</fullName>
                </value>
                <value>
                    <fullName>Could Not Locate Unit</fullName>
                </value>
                <value>
                    <fullName>Customer Not Present</fullName>
                </value>
                <value>
                    <fullName>Insufficient Parts/Tools</fullName>
                </value>
                <value>
                    <fullName>Not Enough Time</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Unable to Attend Site</fullName>
                </value>
                <value>
                    <fullName>Adverse Weather</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Could Not Access Upstream Supply</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Could Not Diagnose</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Engineer Sickness</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Insufficient Materials</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Insufficient Supply</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Insufficient Tools</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Outlander Issue</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Test</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Unsafe Working Environment</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_SA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is checked if the service appointment is Main Service Appointment</description>
        <label>Main SA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Case__r.Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products_Summary__c</fullName>
        <label>Products Summary</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start_Date__c</fullName>
        <formula>SchedStartTime</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scheduled Start (Date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <label>Technician</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aress7/src/classes/CloneSA.cls
global class CloneSA {
    webservice static String cloneME(String SAId){
        
        ServiceAppointment m = [SELECT Id, OwnerId, AppointmentNumber, 
            LastViewedDate, LastReferencedDate, ParentRecordId, 
            ParentRecordType, AccountId, WorkTypeId, ContactId, Street, City, State, PostalCode, Country, StateCode,CurrencyIsoCode,
            CountryCode, Latitude, Longitude, GeocodeAccuracy, Address, Description, EarliestStartTime, DueDate,
            Duration, ArrivalWindowStartTime, ArrivalWindowEndTime, Status, SchedStartTime, SchedEndTime, ActualStartTime,
            ActualEndTime, ActualDuration, DurationType, DurationInMinutes, ServiceTerritoryId, Subject, 
            ParentRecordStatusCategory, StatusCategory, ServiceNote, FSL__Appointment_Grade__c, FSL__Auto_Schedule__c,
            FSL__Emergency__c, FSL__GanttColor__c, FSL__GanttLabel__c, FSL__InJeopardyReason__c, FSL__InJeopardy__c,
            FSL__InternalSLRGeolocation__Latitude__s, FSL__InternalSLRGeolocation__Longitude__s, 
            FSL__InternalSLRGeolocation__c, FSL__IsFillInCandidate__c, FSL__IsMultiDay__c, FSL__MDS_Calculated_length__c,
            FSL__MDT_Operational_Time__c, FSL__Pinned__c, FSL__Prevent_Geocoding_For_Chatter_Actions__c, 
            FSL__Related_Service__c, FSL__Same_Day__c, FSL__Same_Resource__c, FSL__Schedule_Mode__c, 
            FSL__Schedule_over_lower_priority_appointment__c, FSL__Scheduling_Policy_Used__c, FSL__Time_Dependency__c,
            FSL__UpdatedByOptimization__c, FSL__Virtual_Service_For_Chatter_Action__c, Customer_Confirmation__c,
            Actual_Duration_Hours__c, Case__c, Incomplete_Reason_Other__c, Incomplete_Reason__c, Main_SA__c,
            Opportunity__c, Products_Summary__c, Technician__c, Arrival_Window_End_Time__c, Arrival_Window_Start_Time__c,
            Scheduled_Start_Date__c, Scheduled_Start_Time_Minute__c, Scheduled_Start_Time__c, Technician_Email__c FROM ServiceAppointment WHERE ID =: SAId];
        
    
        ServiceAppointment m1 = new ServiceAppointment();
        m1.OwnerId = m.OwnerId;
        m1.CurrencyIsoCode = m.CurrencyIsoCode;
        m1.ParentRecordId = m.ParentRecordId;
        m1.ContactId = m.ContactId;
        m1.Street = m.Street;
        m1.City = m.City;
        m1.State = m.State;
        m1.PostalCode = m.PostalCode;
        m1.Country = m.Country;
        m1.CountryCode=m.CountryCode;
        m1.StateCode = m.StateCode;
        m1.CountryCode = m.CountryCode;
        m1.Latitude = m.Latitude;
        m1.Longitude = m.Longitude;
        m1.GeocodeAccuracy = m.GeocodeAccuracy;
        m1.Description = m.Description;
        m1.EarliestStartTime = m.EarliestStartTime;
        m1.DueDate = m.DueDate;
        m1.Duration = m.Duration;
        m1.ArrivalWindowStartTime = m.ArrivalWindowStartTime;
        m1.ArrivalWindowEndTime = m.ArrivalWindowEndTime;
        m1.Status = 'Unassigned';
        m1.SchedStartTime = m.SchedStartTime;
        m1.SchedEndTime = m.SchedEndTime;
      //  m1.ActualStartTime = m.ActualStartTime;
      //  m1.ActualEndTime = m.ActualEndTime;
     //   m1.ActualDuration = m.ActualDuration;
        m1.DurationType = m.DurationType;
        m1.ServiceTerritoryId = m.ServiceTerritoryId;
        m1.Subject = m.Subject;
        m1.ServiceNote = m.ServiceNote;
        m1.Customer_Confirmation__c = false;
        m1.Case__c = m.Case__c;
        m1.Incomplete_Reason_Other__c = m.Incomplete_Reason_Other__c;
        m1.Incomplete_Reason__c = m.Incomplete_Reason__c;
        m1.Main_SA__c = False;
        m1.Products_Summary__c = m.Products_Summary__c;
        m1.Technician__c = m.Technician__c;
        m1.Technician_Email__c  = m.Technician_Email__c ;
        insert m1;
        //String m1Id = m1.Id;
        //m1Id = m1Id.substring(0,m1Id.length() - 3);
        //System.debug('m1Id -> '+m1Id);
        //return String.valueOf( new PageReference('/'+m1.Id).getUrl());
        return m1.Id;
    }
}